### ISSUE TITLE
FAILED (Syntax error in file name, folder name or volume label. (Os error 123))

### ISSUE THREAD

**Issue by ZarusMods** [BLAKE3-team/BLAKE3#106]
Well in title. OS is Windows 10.

**Comment by oconnor663** [comment]
Please be more respectful of our time when you ask questions. Without detailed steps to reproduce the problem you're seeing, there's no possible way we could know what's causing it or give you useful advice. This process of asking clarifying questions back at you (what I'm doing now) is time-consuming and energy-draining.

**Comment by CRYPTOBRIGHTBUTTERFLY** [comment]
> Please be more respectful of our time when you ask questions. Without detailed steps to reproduce the problem you're seeing, there's no possible way we could know what's causing it or give you useful advice. This process of asking clarifying questions back at you (what I'm doing now) is time-consuming and energy-draining. Please include all the details up front, without waiting to be asked. If you need to include code samples to make the problem reproducible, please make sure the code is runnable (it doesn't depend on code you haven't included) and also minimal (a couple dozen lines at most). It takes time and effort to reduce a problem to simple examples like this, and we need you to help us by putting in that time and effort before you ask a question.

Are you referring to me?

**Comment by ZarusMods** [comment]
I gathered some info about my error. It is problem with Windows self. Windows limits Unicode path names. In win 10 it doesn't allow two or more backslashes.
