### ISSUE TITLE
C implementation build on Linux x86_64 produces binaries with executable stack

### ISSUE THREAD

**Issue by tristanheaven** [BLAKE3-team/BLAKE3#109]
Due to some GNU legacy/compatibility reasons, if an object file doesn't have a `.note.GNU-stack` section, it is assumed to require an executable stack when linked.

If the executable stack is not actually required, the solution is to add something like this into every .S file:
```
#if defined(__linux__) && defined(__ELF__)
.section .note.GNU-stack,"",%progbits
#endif
```
Using the example program from the README, the result can be checked with the `execstack` tool, or by inspecting the /proc/$(pidof example)/maps of the running process:

Before
```
X example
7ffde499b000-7ffde49bc000 rwxp 00000000 00:00 0                          [stack]
```
After
```
- example
7ffdf5616000-7ffdf5637000 rw-p 00000000 00:00 0                          [stack]
```

**Comment by sneves** [comment]
Ugh, I forgot about this. I'll fix this promptly. The question is, is this behavior also the default on the BSDs? I couldn't find a straight answer.

**Comment by DimitryAndric** [comment]
> Ugh, I forgot about this. I'll fix this promptly. The question is, is this behavior also the default on the BSDs? I couldn't find a straight answer.

Yes, it does, at least for FreeBSD. We use the same `.note.GNU-stack` section to signal a non-executable stack. (That said, newer linkers seem to be starting to ignore these sections, and mark the final executable with an executable stack only if you very explictly ask for them. But still, older linkers will still require these sections.)
