### ISSUE TITLE
impl digest::* for Blake3?

### ISSUE THREAD

**Issue by WildCryptoFox** [BLAKE3-team/BLAKE3#11]
It'd be really nice for BLAKE3 to follow RustCrypto's [digest](https://docs.rs/digest/) crate to allow for BLAKE3 to substitute other functions in generic code.

~~`Hasher` is a poor name here, `Blake3` would be cleaner. I expect to see many instances of `use blake3::Hasher as Blake3`. A type alias suffices to avoid a breaking change `type Hasher = Blake3`~~

These traits **can be implemented without a breaking change**. However, it'd be cleaner to only implement digest's traits and any other breaking changes could be batched. The release is early and much more usage will come with the digest traits implemented.

Great work BLAKE3-team!

**Comment by WildCryptoFox** [comment]
@elichai Can you please explain the thumbs down?

**Comment by oconnor663** [comment]
> `Hasher` is a poor name here, `Blake3` would be cleaner.

My understanding is that the official style guidelines say differently: https://doc.rust-lang.org/1.0.0/style/style/naming/README.html#avoid-redundant-prefixes-[rfc-356]

> It'd be really nice for BLAKE3 to follow RustCrypto's digest crate to allow for BLAKE3 to substitute other functions in generic code.

I'm willing to review a PR along these lines, if someone submits one. I'd prefer to have it gated behind an optional feature flag, maybe depending on what other crates in the same space have done.

That said, I'm not *suuuper* excited about code that treats hash functions generically. Cryptographic hash functions often provide the same interface without providing the same guarantees. For example, HMAC-MD5 is probably secure in practice (not that anyone should ever risk it), but Ed25519-MD5 is not. Similarly, length extension issues make SHA-2 unsuitable for some applications where SHA-3 or BLAKE2/3 are fine. More broadly, a lot of really nasty practical attacks over the years are downgrade attacks, and supporting multiple algorithms opens you up to that sort of thing.

**Comment by WildCryptoFox** [comment]
There is prefix and there is exact. The name of the thing we're interested in here is Blake3. If all hash functions were named Hasher, they'd need to be accessed as `blake3::Hasher` instead of `Blake3`.

Regarding different hash function properties, I am in favor of semantics carrying marker traits, though others disagree because you can just impl incorrectly... But it'd help reduce errors and keep the requirements explicit and clear.

I want to write generic code so I can provide type aliases for the one or two I'm interested in promoting; while allowing someone who knows what they are doing to substitute the function without forking the whole crate.

**Comment by WildCryptoFox** [comment]
The `digest` crate is popular for cryptography in Rust because the interface is well defined and consistent. The biggest caveat to it is we're stuck with typenum and generic-array's hacks until const-generics land; then most of the rust crypto will hit a breaking change upgrade.

The preference (by evidence) is to just implement the crypto traits directly without any (unless necessary) methods on the concrete type.

I'd be willing to implement it as either in a PR. I just need to know which direction is preferred on your side.

**Comment by elichai** [comment]
> @elichai Can you please explain the thumbs down?

Mostly because of the suggestions to replace the functions with the trait, that means I need to directly import RustCrypto's traits just to be able to use this crate.

Personally I'm not a fan of RustCrypto's abstractions. I think abstractions in cryptographic code turn really fast into vulnerabilities. (there's a reason people always preferred to write crypto code in C rather than C++)

**Comment by WildCryptoFox** [comment]
@elichai The digest crate, et al trait-only crates, are very lightweight, consistent and safe. Why do you believe promoting consistent interfaces invite vulnerabilities?

If you mean @oconnor663 's argument that traits make misuse easier; then I disagree because this misuse is available without the traits. Marker traits can be used to consistently signal certain properties, which actively block misuse by the less informed user; while trusting the implementer of these markers.

I'd rather not expose equivalent functions both on the concrete type and on the trait because this bloats the method namespace, and promotes redundant (and potentially conflicting) documentation. Having only the trait-impl reduces the room for error while promoting generic code.

The only downsides I see to RustCrypto's traits are: the need for typenum and generic-array until const-generics land; and when the abstraction doesn't perform as well. The only example I have for the latter is the `ctr` crate against `aesni`; but this isn't a trait and could be fixed.

**Comment by oconnor663** [comment]
I'm starting to lean towards doing this in a separate wrapper crate. A wrapper type could avoid implementing any inherent methods, while the `blake3` crate itself could avoid taking any extra dependencies. The wrapper crate could also issue an incompatible version bump when const generics land, without forcing `blake3` itself to bump.

Perhaps someone could publish a crate in a separate repo, and later we could look at merging it into this repo? I would be happy to link to such a crate from our README and docs.

**Comment by WildCryptoFox** [comment]
@oconnor663 This would work fine. I might take this up after I've done a handful other things first.

**Comment by phayes** [comment]
Just to pipe up about a use-case here.  I maintain the Full Domain Hash crate (https://github.com/phayes/fdh-rs), which is generic over all cryptographically secure hash functions.   I would need these traits implemented in order to use Blake3 as part of the Full Domain Hash crate.    

The entire `digest` crate is very light weight, and allows great interop, so would encourage it to be used as much as possible.

**Comment by WildCryptoFox** [comment]
@phayes Would BLAKE3's inclusion be an XOF passthrough or would your H->XOF take over still?

**Comment by phayes** [comment]
@WildCryptoFox, 

Full Domain Hash's ability to turn any hash function into an XOF is really not very useful anymore now that we have excellent XOFs like SHAKE and BLAKE.  However, it's still very useful for producing a digest with a restricted domain (the premiere use-case being RSA-blind signatures). 

I've actually got an experimental construction called a [Moving Window Full Domain Hash](https://github.com/phayes/fdh-rs/tree/master/src/movingwindow) that is generic over `digest::ExtendableOutput` to make restricted domain hashing efficient and constant-time.  I'm actually looking for someone who's good at crypto-math to help me write a paper on it. 

All this to say, making cryptography composable by using traits is super useful, especially at the cutting edge.  I'm looking forward to your glue-crate!

**Comment by WildCryptoFox** [comment]
@phayes [Lets move this off-topic chat to a gist.](https://gist.github.com/d1a649463041a93e349c499a43ca33a9)

**Comment by WildCryptoFox** [comment]
@oconnor663 [Done](https://github.com/WildCryptoFox/blake3-digest). Not published because I'd still rather these be defined in the blake3 crate where the clones may be reduced.

**Note**: The digest crate doesn't have any functions which ask for keys or context strings. For these, we might want [`crypto_mac::Mac`](https://docs.rs/crypto-mac/0.7.0/crypto_mac/trait.Mac.html) with the provided `crypto_mac::Mac::new_varkey` overridden to use the internal domain separation.

**Comment by oconnor663** [comment]
I'm leaning towards having this one be a separate crate. Would you be up for publishing as `blake3-digest` or similar on crates.io?

**Comment by phayes** [comment]
I would recommend against putting this in a fully separate crate.   Having all hash functions, by default, implement the defacto-standard hash trait makes inter-crate iterop much easier. 

Having said that, perhaps a compromise could be to put it behind a feature flag?

**Comment by WildCryptoFox** [comment]
@oconnor663 I would be willing to publish it as a separate crate; though like @phayes I'd rather not. You can see the code, it is tiny. I'd rather these traits replace the current exposed API but a feature flag will suffice if you're still against that.

**Comment by dpc** [comment]
[I would also like `Digest` support](https://www.reddit.com/r/rust/comments/exeuiy/rblake2sum_a_recursive_blake2_digest_hash_of_a/fg8iz68/)

**Comment by oconnor663** [comment]
Ok I'm going to stop being stubborn :) Let's get this in.

I just put up a https://github.com/BLAKE3-team/BLAKE3/tree/digest branch. Playing with that, I don't see any significant difference in build times, so I'm leaning towards including the implementations by default without a feature flag. Any objections? We can revisit this before 1.0 in any case.

I'm still not in favor of replacing the inherent API entirely. A few reasons: 1) I don't want to force non-generic callers to import these traits. 2) The `keyed_hash` and `derive_key` functionality doesn't fit into `digest` today, and it would be kind of weird to have those callers use a mixture of inherent and trait-based APIs. 3) The `FixedOutput` and `ExtendableOutput` traits consume a hasher by value, while the inherent `blake3::Hasher::{finalize, finalize_xof}` methods take `&self`. Thoughts on these? Anything I missed?

**Comment by dpc** [comment]
The fact that in cases like this the user has to import some additional traits is indeed annoying, and I wish it was possible to say "if you import my `struct X` you also get `trait Y` imported".

**Comment by oconnor663** [comment]
Here's the issue for that, though it doesn't looks like anyone's picked it up to write a full RFC: https://github.com/rust-lang/rfcs/issues/1880

**Comment by WildCryptoFox** [comment]
@oconnor663 As I've already mentioned `keyed_hash` and `derive_key` match to [`crypto-mac::Mac`](https://docs.rs/crypto-mac/0.7.0/crypto_mac/trait.Mac.html).

Also mentioned previously the `self`/`&self` is just a matter of moving clones; but would be more intrusive to change, especially while keeping the non-trait interface. The extra clones would probably be optimized away. Might be worth a benchmark.

Regarding "importing the traits", this is just `use blake3::{digest::*, crypto_mac::Mac};` as needed. Callers don't need to add the trait crates manually. You could simplify this to `use blake3::prelude::*;` to be lazy too. In either case you can rename the traits to `_` to avoid polluting the namespaces.

**Comment by oconnor663** [comment]
Just landed 9bab77d2cfe2d35e9fcc5b19424ebf865e0c0c2e. Could you guys take a look at it and let me know if everything looks good there? I'll probably push out a release tomorrow.

**Comment by WildCryptoFox** [comment]
@oconnor663 Looks good. No [`crypto-mac::Mac`](https://docs.rs/crypto-mac/0.7.0/crypto_mac/trait.Mac.html) yet but this doesn't need to block on that independent decision! Little surprised digest's `std` isn't default-on though I like it this way, no polluting `default-features`. :)

**Comment by oconnor663** [comment]
Just shipped as v0.1.4. I went ahead and added `crypto_mac::Mac`. Please let me know if this is working as intended for everyone.

**Comment by WildCryptoFox** [comment]
@oconnor663 Looks good. Though it is common to re-export these crates such that a consuming crate doesn't need to specify and keep updated the `digest` and `crypto-mac` versions in their `Cargo.toml`. If two versions of a crate are compiled as your dependencies, you don't want to mix them as that leads to obscure type errors like "X does not implement Y, but X does implement Y" (referring to different versions of Y). Cargo usually does a good additive job here, it only hits this edge case with complex dependency graphs where someone is behind a major version.

```rust
pub use crypto_mac;
pub use digest;
```

**Comment by oconnor663** [comment]
Good point, added 24071db3463f29a6ad6173e3aea62b0f1497b5bc.

**Comment by WildCryptoFox** [comment]
@oconnor663 https://github.com/BLAKE3-team/BLAKE3/commit/24071db3463f29a6ad6173e3aea62b0f1497b5bc#r37114191

**Comment by oconnor663** [comment]
@WildCryptoFox responding to https://github.com/BLAKE3-team/BLAKE3/issues/13#issuecomment-582003078 here, because I think it might've landed on the wrong issue thread?

I intentionally avoided implementing `crypto_mac::Mac::new_varkey`. The keyed hashing mode only supports 256-bit keys, and the default behavior of returning an error in that case is correct. The key derivation mode does accept key material of any length, but that requires a context string that the `crypto_mac` API doesn't currently have a place for. (The security requirements of the key derivation mode are also relatively specific, and I'd be hesitant to expose that mode through a trait API that didn't document the same requirements.)

**Comment by WildCryptoFox** [comment]
@oconnor663 Implementing it or not; the function is there as a provided method. Implementing it allows you to override the default keying method to use domain separation as intended.

**Comment by oconnor663** [comment]
I'm not sure I follow your last comment. The default implementation of `new_varkey` returns an error whenever the key length is not equal to `Self::KeySize`. I believe this behavior is correct for `blake3::Hasher`, so I did not override it.

**Comment by WildCryptoFox** [comment]
@oconnor663 Ah. My mistake. Okay, yes, this looks good.
