### ISSUE TITLE
b3sum: macOS version support (backward compatibility)

### ISSUE THREAD

**Issue by JayBrown** [BLAKE3-team/BLAKE3#111]
Is there any info which versions of macOS and OS X are supported, i.e. on which systems the pre-compiled b3sum CLI (available for download here) will work on? (Note: I'm not talking about Big Sur, but backward compatibility, i.e. the oldest OS b3sum supports.)

For what it's worth, it was working fine on Mojave (10.14), and is currently working fine on Catalina (10.15).

However, on Snow Leopard (10.6.8) I'm getting an `illegal instruction` error when trying to execute b3sum.

**Comment by oconnor663** [comment]
I don't think anyone's done comprehensive testing, no. Currently the only macOS version we test in CI is "whatever GitHub Actions is using."

I'm a little surprised to see an illegal instruction error, since b3sum should be detecting processor SIMD support at runtime and avoiding any unsupported code. Any chance you could grab a backtrace of that crash from lldb?

**Comment by sneves** [comment]
My money is on the illegal instruction being `ud2`, after reaching some kind of unexpected or unreachable state.

**Comment by JayBrown** [comment]
It was quite a wild ride to get the Lion Command Line Tools and python 2.7 to work on Snow Leopard, but here's the lldb output:

```
lldb /usr/local/bin/b3sum
Current executable set to '/usr/local/bin/b3sum' (x86_64).
(lldb) process launch
Process 1723 launched: '/usr/local/bin/b3sum' (x86_64)
error: initial process state wasn't stopped: exited
(lldb) run
Process 1734 launched: '/usr/local/bin/b3sum' (x86_64)
Process 1734 stopped
* thread #1: tid = 0x2c03, 0x00007fff5fc01028 dyld`_dyld_start, stop reason = EXC_BAD_ACCESS (code=1, address=0xfffffffffffffff8)
    frame #0: 0x00007fff5fc01028 dyld`_dyld_start
dyld`_dyld_start:
-> 0x7fff5fc01028:  pushq  $0
   0x7fff5fc0102a:  movq   %rsp, %rbp
   0x7fff5fc0102d:  andq   $-16, %rsp
   0x7fff5fc01031:  movq   8(%rbp), %rdi
```

**Comment by gdbinit** [comment]
No Rust support for Snow Leopard? https://github.com/rust-lang/release-team/issues/2
dyld had a lot of updates so most probably the compiled version is incompatible with Snow Leopard.

**Comment by JayBrown** [comment]
Please note: I do not _need_ it to be compatible with SnowLeo—I was just testing it on that system. Compatibility with OS X 10.8 would be more important. (I'm bundling it with a Platypus app, which will not run on 10.7 and earlier anyway.)

**Comment by gdbinit** [comment]
So install it and test it :-]

**Comment by JayBrown** [comment]
Easier said than done… but I will try and eventually report back.

**Comment by JayBrown** [comment]
I can confirm that **b3sum** works fine on **OS X 10.8.5 (Mountain Lion)**.

**Comment by JayBrown** [comment]
Can also confirm that it works fine on **OS X 10.9.5 (Mavericks)**.

**Comment by oconnor663** [comment]
Thanks for doing this testing! I'll close this issue, but feel free to reopen it.
