### ISSUE TITLE
Consider deprecating the C-string version of blake3_hasher_init_derive_key

### ISSUE THREAD

**Issue by k0001** [BLAKE3-team/BLAKE3#115]
Contrary to all other public parameters in the various BLAKE3 functions, the `blake3_hasher_init_derive_key` function treats a `0x00` byte in its `context` parameter specially, meaning that users of BLAKE3 as a key derivation function need to take special care when calling this function that go beyond following the guidelines for context string design, lest a chunk of the specified `context` after a `0x00` byte is silently ignored.

In practice, this means that having a `0x00` byte in the context must be considered an error by any function making use `blake3_hasher_init_derive_key` whenever said function takes the context as a binary blob from a third party source. Above all, this affects bindings in languages that don't use the C string convention, which, moreover, will need to copy over the context bytes to create a `0x00`-terminated C string before being able to call `blake3_hasher_init_derive_key`.

Not being able to treat `context` as an opaque binary blob leads to a more cumbersome user experience for no significant gain, particularly if we consider that other non-alphanumeric bytes such as `0x01` or `0x07` are not treated specially beyond an implicit recommendation against them in the context string design guidelines. That is, the choice to treat `0x00` specially seems rather arbitrary. Generally speaking, introducing errors in an API leads to a more cumbersome user experience, and removing the possibility of this being an error would simplify the key derivation function.

To contrast, in HKDF, all the input parameters (info, salt, ikm) can be treated as opaque binary blobs of a given length. This leads to a better user experience compared to BLAKE3's key derivation, since users of HKDF don't have to worry about checking these parameters for the absence or presence of a particular byte. They can expect HKDF to always succeed for any given input.

It's clear that `blake3_hasher_init_derive_key` is optimized for dealing with _literal_ C strings. But that's only one use case. When you consider bindings to this library, and the fact that a terminating `0x00` could be present or absent (!!!) in a `context` comming from an untrusted source, the current C string solution is not ideal.

In #114 I introduced `blake3_hasher_init_derive_key_len` as a separate function that solves the problem of bindings to this library having to copy over the context bytes so that they can add a `0x00` at the end, if using `blake3_hasher_init_derive_key`. However, as long as the main `blake3_hasher_init_derive_key` works with C strings, care should be taken so that the `context` given to `blake3_hasher_init_derive_key_len` doesn't include a `0x00` byte, for compatibility with different implementations of BLAKE3. 

My recommendation is to get rid of `blake3_hasher_init_derive_key` as it is today, and rename the proposed `blake3_hasher_init_derive_key_len` to `blake3_hasher_init_derive_key`. This would be a backwards incompatible change to the extent that rather than `blake3_hasher_init_derive_key(h, foo)`, users would have to write `blake3_hasher_init_derive_key(h, foo, strlen(foo))` if they want exactly the same behavior as before, but this wouldn't go silently unnoticed, seeing how we'd be changing the number of parameters in this function, causing compilation errors downstream, which is good. This change wouldn't be very invasive, in any case, seeing how BLAKE3 is not being offered as a static/shared library yet. Alternatively, if backwards compatibility is desired, the two functions could continue to be offered, but it should be clear that the C string version is merely a convenience for literal C strings. That is, documentation should be improved so that downstream bindings and users can make the right decisions.

**Comment by oconnor663** [comment]
There's been some discussion of this before in this thread: https://github.com/BLAKE3-team/BLAKE3/issues/13

> Not being able to treat context as an opaque binary blob leads to a more cumbersome user experience for no significant gain

I won't copy/paste all of the discussion behind that link, but I want to try to summarize it. In my mind, there is a significant gain. The security requirement that **context string must be hardcoded** is quite important, but it's also unusual, easy to miss, and difficult to enforce at the API level. The decision to use each language's "regular string type" for the context (that is, my decision so far as an implementer, though it's not something we mention in the BLAKE3 spec) is an intentional speed bump. The thinking is that, if you're doing something that requires arbitrary bytes in the context parameter, you're almost certainly violating that security requirement. If the string type causes an impedance mismatch that leads developers to read the docs and learn about the requirement, that's a good thing.

An important design detail here is that there's almost no difference between `derive_key(context, material)` and `keyed_hash(hash(context), material)`. They're 99% the exact same codepath, except that `derive_key` is domain separated using a couple of internal bitflags. In that sense, domain separation is the _sole purpose_ of `derive_key`, and the usage conventions that preserve domain separation between uncoordinated callers are an essential part of the design. I think the requirement that "the context string must be hardcoded" can seem a little bit like putting the training wheels on. But I want to emphasize that the `derive_key` API has no practical value at all unless everyone follows the same requirements, which in turn means that the requirements have to be simple and clear.

If there's a caller that wants to hash to arbitrary-length byte streams, a la HMAC or HKDF, I'd advise them to use a construction like `keyed_hash(hash(context), material)`. In that case, they're taking domain separation into their own hands, and they should probably follow the usual crypto advice of using each secret with only one algorithm, to avoid any possible interactions. If and only if they have a hardcoded (and globally unique, and application-specific) context string, then I'd advise them to use `derive_key` with that parameter as part of whatever larger construction they're designing.

**Comment by k0001** [comment]
> The security requirement that the context string must be hardcoded is quite important, …

I wholeheartedly **agree** on the importance of the context being a well-known, hardcoded string, ideally statically known at compile time. I am not challenging that. The gains from this are clear, as described in the BLAKE3 paper and the issue you linked. What I'm challenging is the **abstraction** chosen for this.

> …  but it's also unusual, easy to miss, and difficult to enforce at the API level.

Exactly! **C is not the place to come up with such abstraction.** Every language out there can cope with the idea of a statically known, hardcoded string, but almost none of them use the C string abstraction. However, if the official C implementation fully embraces this abstraction, and makes it the **only** alternative available through its API, then every other implementation or binding of BLAKE3 must accommodate for compatibility reasons. And this, in turn, makes supporting the BLAKE3 key derivation function harder that it needs to be, because the C string abstraction is not without its complications. Namely, it treats `\x00` specially, forcing every other language to treat it specially, too.

Consider the following example. It could be JavaScript, Python, Haskell, etc., it doesn't matter which language.

```
context_foo = "Fancy App - August 31, 2020 - Key \x01 for the foo thing";

context_bar = "Fancy App - August 31, 2020 - Key \x00 for the bar thing";
```

Both `context_foo` and `context_bar` are hardcoded bytes that respect the BLAKE3 context design guidelines. There's nothing wrong with any of them insofar as the purpose of the derivation context is concerned, and BLAKE3 can technically deal with both of them just fine. However, given the current API in the C library, `context_bar` must be avoided for compatibility reasons. Why? There's no fundamental reason why.

One might argue that it's silly to include either of the non-alphanumeric `\x00` or `\x01` in the context string, but from a cryptographic point of view, insofar as BLAKE3 is concerned, one can't argue that one is more silly than the other. Either both are equally silly, or both are equally fine. And this is my point: `\x00` is being treated _specially_ by the current C API, and this complicates things downstream, mandating additional checks, and generally preventing the BLAKE3 key derivation function from being error-proof when it could otherwise function for 100% of the inputs it receives, as HKDF does. 

Again, as the example above showed, hardcoding some bytes does not mean “avoid writing `\x00`, but also add a `\x00` at the end”. That's just a C thing that can can be supported just fine as a subset of the general case, without introducing any backwards incompatibility. Here's how:

```c
void general_version(bytes, bytes_len);

void cstring_version(str) { 
    general_version(str, strlen(str)); 
}
```

This is essentially the change that I submitted in #114.

To put things a bit in perspective: For whatever reasons, BLAKE2 also suffers from a key derivation functions whose input parameters aren't particularly user friendly (e.g., not being able to use arbitrary length inputs), and presumably this contributes to BLAKE2's key derivation function not being used too often, and instead, the BLAKE2 hashing function being used in combination with HKDF. I know I have avoided BLAKE2's key derivation function for this exact reason. BLEAK3's key derivation algorithm, in contrast, is in theory very user friendly, and could compete with HKDF in terms of usability and adoption just fine. However, currently, the artificial limitations in the C API are making this algorithm less user friendly than it needs to be, in the sense that not all binary blobs are valid inputs to the algorithm, forcing implementations to treat this one byte specially, potentially failing for some particular choices of input, even if these are hardcoded.

And, yes, in principle one could avoid BLAKE3's key derivation function and use `keyed_hash(hash(context), material)` instead. However, unless I missed something, because of those bitflags you mention, this results in a different hash than that of `derive_key(context, material)`, making the two APIs incompatible with each other. And, as you say, this forces users to take domain separation into their own hands, leaving BLAKE3 without a _cannonical_ key derivation function that's both straightforward **and error-proof**, perhaps pushing users back to HKDF.

So, again, to reiterate my points:

1. **Harcoding the context is a great idea.** Please, let's continue encouraging users to hardcode the context bytes. The context must consist of well-known bytes.

2. **The C string is not the proper abstraction for the key derivation function** because:

    1. … it forces the entire BLAKE3 ecosystem to treat the `\x00` byte specially.

    2. … it prevents the BLAKE3 key derivation function from being error-proof, even when those context strings are hardcoded, in languages other than C.

    3. … it forces other languages to copy over bytes and write a `\x00` at the end before calling the C library.
    
3. **The C string can be supported** without necessarily making it the canonical abstraction for the key derivation function.

4. **Let's consider the wider BLAKE ecosystem**, not just the users writing literally in the C language.

5. **Let's prevent fragmentation** by making sure there is one canonical key derivation function which is simple to use and error-proof. Currently, only users writing literal C strings have those benefits.

My goal with this conversation is to make it easier for the BLAKE3 key derivation function to gain adoption. As things stand today, not being able to specify the bytes and the number of bytes separately is an obstacle.

**Comment by oconnor663** [comment]
Ok now I think I understand your point better, and I agree. You're talking mostly about writing bindings for other languages, while I'm talking mostly about writing applications. Taking an arbitrary byte array is the Wrong Thing for application code, but it's the Right Thing for implementing bindings. So we probably need to provide both APIs, and then do our best to distinguish between them in documentation. Looks like you're way ahead of me with #114 :)

I might bikeshed a little bit and suggest the name `blake3_hasher_init_derive_key_raw`. That might be a stronger suggestion that it's not the higher-level API that applications should reach for.

I will have more time to review this properly tonight, or maybe in the next couple days. Apologies for keeping you waiting.

**Comment by oconnor663** [comment]
Maybe you could say more about why you're in favor of removing the existing API. My first thought is that we should keep it, as the preferred API for applications written in C.

**Comment by sneves** [comment]
> BLAKE2 also suffers from a key derivation functions

BLAKE2 does not have a key-derivation function; it has a keyed mode, which takes a uniformly random key. Using HKDF for the purpose of deriving this key is a bit over the top, though.

Anyway, I don't have a dog in this fight, but if I wanted to argue for the current API I'd say the input to the key derivation must be a valid UTF-8 string, in which case all other languages would need to be C-compliant anyway.

**Comment by k0001** [comment]
> Ok now I think I understand your point better, and I agree. 

Great news! I apologize for the confusion if I wasn't clear the first time =)

> Maybe you could say more about why you're in favor of removing the existing API. My first thought is that we should keep it, as the preferred API for applications written in C.

Removing the C string version is not strictly necessary. I think there is some value in continuing to offer the C string version, since it simplifies the use of this function for users writing C literally, as you have described multiple times. My preference would be too only export a single version so as to keep the API as minimal as possible, exporting only primitive operations, and without any redundancies. However, continuing to export the C string version as a convenience should be fine too, provided its documentation explicitly mentions that it is a **convenience for literal C strings**.

> I might bikeshed a little bit and suggest the name `blake3_hasher_init_derive_key_raw`. That might be a stronger suggestion that it's not the higher-level API that applications should reach for.

That's fine by me. Again, provided that the documentation for the C string version explicitly describes it as a _convenience_ for the common use case in C, and highlighting `blake3_hasher_init_derive_key_raw` as the general case that is expected to be supported across different implementations. I'll update #114 to include these changes.

> BLAKE2 does not have a key-derivation function; it has a keyed mode, which takes a uniformly random key. Using HKDF for the purpose of deriving this key is a bit over the top, though.

Oh, I meant the function that takes as input these “personal bytes”, which `libsodium`, for example, uses as key derivation function.

> Anyway, I don't have a dog in this fight, but if I wanted to argue for the current API I'd say the input to the key derivation must be a valid UTF-8 string, in which case all other languages would need to be C-compliant anyway.

I agree that this is a sane **recommendation**, and I think it would be great to mention this in the docs. But, to make bindings and implementations easier, as described before, BLAKE3 should blindly accept whatever bytes are given to it as context (which, as per the guidelines, 99% of the time will be a hardcoded string, anyway, and not a random string from an untrusted source).

**Comment by k0001** [comment]
Changes made in #114

**Comment by oconnor663** [comment]
Closing as #114 has landed.
