### ISSUE TITLE
for x86 C-implementation, is *only* gcc and MSVC supported?

### ISSUE THREAD

**Issue by divinity76** [BLAKE3-team/BLAKE3#126]
reading through https://github.com/BLAKE3-team/BLAKE3/blob/master/c/blake3_dispatch.c i see
```c
#if defined(IS_X86)
#if defined(_MSC_VER)
#include <intrin.h>
#elif defined(__GNUC__)
#include <immintrin.h>
#else
#error "Unimplemented!"
#endif
#endif
```
that looks to me like 

> for x86, MSVC and gcc is supported. on anything else it will explicitly refuse to compile

(which probably sucks for Clang / Intel ICC / IBM C / etc users, and any would-be-integrators who want to support more than just MSVC+gcc)

so.. is it correct to say that, for x86, the c-version of the official blake3 implementation only supports gcc and MSVC?

**Comment by sneves** [comment]
Both Clang and the Intel compiler will set `__GNUC__` (or `_MSC_VER`, depending on the platform).

**Comment by divinity76** [comment]
@sneves oh well that helps a lot, then the "big 3" are covered at least (gcc, clang, and MSVC)

**Comment by divinity76** [comment]
that's probably good enough (until a TinyC user comes along? in which case a dedicated issue can be opened)

closing.
