### ISSUE TITLE
has blake3_avx512.c been test-compiled on MSVC?

### ISSUE THREAD

**Issue by divinity76** [BLAKE3-team/BLAKE3#127]
the start of the file currently reads
```
#include "blake3_impl.h"

#include <immintrin.h>
```
does that actually compile on MSVC? i think it's called `intrin.h` in on MSVC and `immintrin.h` on gcc-like compilers, as implied by both c/blake3_dispatch.c and https://docs.microsoft.com/en-us/cpp/intrinsics/intrinsics-available-on-all-architectures?view=vs-2019

or is the file perhaps somehow excluded from compiling on MSVC? or

**Comment by divinity76** [comment]
nvm, they're both present on MSVC

**Comment by oconnor663** [comment]
For what it's worth, we do CI testing on Linux (GCC), macOS (Clang), and Windows (both GCC and MSVC). A lot of it is testing Rust code, but you'll see sections described as "cargo test C bindings" that are actually exercising C code via a small Rust test harness. (There are also pure C tests using a Makefile, but currently we only run those on Linux.) Here's an example run: https://github.com/BLAKE3-team/BLAKE3/actions/runs/311864006
