### ISSUE TITLE
can we make version available in /c/blake3.h ?

### ISSUE THREAD

**Issue by divinity76** [BLAKE3-team/BLAKE3#130]
just some
```
#define BLAKE3_VERSION_STRING "0.3.7"
```
or something, mirroring the version number found in /Cargo.toml

(i am in a situation where some C code bundling the C version of BLAKE3 want to know which version it is bundling, that project is bundling 0.3.7's `blake3_portable.c` in it's own repository, but allows a `./configure --with-blake3-upstream-c-source-dir=DIR` for users who want SSE/AVX/etc)

**Comment by oconnor663** [comment]
Sure, this seems like a good idea. Should we make it a static string, so that dynamically linked programs can ask about the version at runtime? In that case, does it need to be a function?

**Comment by sneves** [comment]
Probably both. Something like
```
#define BLAKE3_VERSION_STRING "0.3.7"
const char * blake3_version(void);
```
in `blake3.h` and
```
const char * blake3_version(void) {
  return BLAKE3_VERSION_STRING;
}
```
in `blake3.c`.

**Comment by oconnor663** [comment]
@divinity76 if you want to put up a PR for this, you'll get an immediate 👍 :)

**Comment by divinity76** [comment]
thanks guys, 
implemented in PR https://github.com/BLAKE3-team/BLAKE3/pull/131 , 
closing this issue.
