### ISSUE TITLE
Performance against SHA256 doesn't match the whitepaper

### ISSUE THREAD

**Issue by xoofx** [BLAKE3-team/BLAKE3#140]
Hey,

While implementing a wrapper of BLAKE3 for .NET ([Blake3.NET](https://github.com/xoofx/Blake3.NET)) I have ran some benchmarks against SHA256 but I have found that the numbers don't quite match what I was reading from the whitepaper:

|     Method |       N |          Mean |        Error |       StdDev |
|----------- |-------- |--------------:|-------------:|-------------:|
|     **Blake3** |       **4** |      **77.86 ns** |     **0.332 ns** |     **0.310 ns** |
|     SHA256 |       4 |     244.31 ns |     1.157 ns |     1.082 ns |
|     **Blake3** |     **100** |     **125.60 ns** |     **0.497 ns** |     **0.440 ns** |
|     SHA256 |     100 |     279.82 ns |     1.853 ns |     1.734 ns |
|     **Blake3** |    **1000** |     **888.90 ns** |     **0.873 ns** |     **0.681 ns** |
|     SHA256 |    1000 |     700.81 ns |     2.078 ns |     1.842 ns |
|     **Blake3** |   **10000** |   **3,508.37 ns** |    **23.411 ns** |    **21.899 ns** |
|     SHA256 |   10000 |   4,922.90 ns |    14.360 ns |    13.432 ns |
|     **Blake3** |  **100000** |  **22,109.48 ns** |    **47.699 ns** |    **39.830 ns** |
|     SHA256 |  100000 |  48,655.78 ns |   102.273 ns |    95.666 ns |

All of the above are single threaded and using `blake3::hash`

For example:

- Around 1000 bytes, strangely BLAKE3 is performing almost 20% worse than SHA256.
- Around 100,000 bytes, BLAKE3 is performing only twice as fast as SHA256

So my question are: 
- Are these numbers matching what you would expect? Any ideas what could be wrong? (Did I mess up the Rust configuration of BLAKE3 [here](https://github.com/xoofx/Blake3.NET/tree/master/lib/blake3_dotnet)?)
- Against which implementation of SHA256 did you run your benchmark?

**Comment by oconnor663** [comment]
My guess is that the difference is SHA-256 hardware acceleration. The benchmarks in the paper were run on a Cascade Lake-SP processor, the latest and greatest available from AWS at the time. (The specific implementation was OpenSSL.) That microarchitecture supported AVX-512, which is very good for BLAKE3, but it didn't yet support the SHA extensions, which is of course bad for SHA-256. If you're running benchmarks on a very recent Intel chip (Ice Lake), or on an AMD chip from the past couple years, you will have the SHA extensions, and you'll see SHA-256 performing better.

**Comment by xoofx** [comment]
Oh, never realized about these extensions, it makes completely sense about my numbers.
So basically, SHA256 is cheating! 😅
Looking forward to the BLAKE3 extensions now!

**Comment by sneves** [comment]
What chip was this benchmark performed in?

**Comment by xoofx** [comment]
An AMD Ryzen 9 3900X, so yeah, it has this SHA extension, will try to run it on my old macbook pro tomorrow to compare

**Comment by xoofx** [comment]
So confirmed with an `Intel Core i7-4980HQ CPU 2.80GHz (Haswell)`, the figures are more matching the whitepaper:

|     Method |       N |            Mean |         Error |        StdDev |          Median |
|----------- |-------- |----------------:|--------------:|--------------:|----------------:|
|     **Blake3** |       **4** |        **85.06 ns** |      **1.704 ns** |      **2.154 ns** |        **83.55 ns** |
|     SHA256 |       4 |       531.82 ns |      0.842 ns |      0.788 ns |       531.85 ns |
|     **Blake3** |     **100** |       **145.12 ns** |      **2.899 ns** |      **4.064 ns** |       **142.56 ns** |
|     SHA256 |     100 |       803.32 ns |     11.420 ns |      8.916 ns |       797.37 ns |
|     **Blake3** |    **1000** |       **999.01 ns** |     **19.658 ns** |     **26.908 ns** |       **984.60 ns** |
|     SHA256 |    1000 |     4,489.81 ns |     84.032 ns |     78.603 ns |     4,525.27 ns |
|     **Blake3** |   **10000** |     **4,099.92 ns** |     **49.985 ns** |     **46.756 ns** |     **4,121.94 ns** |
|     SHA256 |   10000 |    40,799.82 ns |    769.102 ns |  1,386.850 ns |    41,460.32 ns |
|     **Blake3** |  **100000** |    **28,491.58 ns** |    **394.692 ns** |    **369.195 ns** |    **28,498.05 ns** |
|     SHA256 |  100000 |   408,581.45 ns |  2,359.416 ns |  2,207.000 ns |   409,059.91 ns |

Thanks for the clarification!

**Comment by oconnor663** [comment]
Sure thing! These comparisons are super tricky. (Another issue that I didn't even account for in the paper is that SHA-256 pads its input, so it's slightly unfair to compare it to BLAKE3 at 64 bytes, because that's two blocks of SHA-256 but only one block of BLAKE3. The longest SHA-256 input that's still one block of compression is 55 bytes I think.)
