### ISSUE TITLE
B3sum doesn't work with folders with space on Windows

### ISSUE THREAD

**Issue by ZeusMods** [BLAKE3-team/BLAKE3#144]
Hello, today I have experienced the problem. The problem is that b3sum doesn't work correctly with folders which have spaces and giving out the (os error 2) the error is fixed only when you are using folders without any space in them.

**Comment by sneves** [comment]
Paths with spaces must be quoted; this is part of how command lines are processed in Windows. For example,
```
C:\>b3sum_windows_x64_bin.exe C:\Program Files\LLVM\bin\clang.exe
b3sum: C:\Program: The system cannot find the file specified. (os error 2)
b3sum: Files\LLVM\bin\clang.exe: The system cannot find the path specified. (os error 3)
C:\>b3sum_windows_x64_bin.exe "C:\Program Files\LLVM\bin\clang.exe"
cb1a70b4bd050ecea32dd078e780aaaaebea55b2b6ef2c308e59f8a7c9acf6fb  C:/Program Files/LLVM/bin/clang.exe
```

**Comment by oconnor663** [comment]
I think if you use <tab> to autocomplete the name of the folder, the terminal will automatically add quotes for you.

**Comment by ZeusMods** [comment]
> Paths with spaces must be quoted; this is part of how command lines are processed in Windows. For example,
> 
> ```
> C:\>b3sum_windows_x64_bin.exe C:\Program Files\LLVM\bin\clang.exe
> b3sum: C:\Program: The system cannot find the file specified. (os error 2)
> b3sum: Files\LLVM\bin\clang.exe: The system cannot find the path specified. (os error 3)
> C:\>b3sum_windows_x64_bin.exe "C:\Program Files\LLVM\bin\clang.exe"
> cb1a70b4bd050ecea32dd078e780aaaaebea55b2b6ef2c308e59f8a7c9acf6fb  C:/Program Files/LLVM/bin/clang.exe
> ```

Since for me this is a batch script it's like goes to the temp folder with check flag

here
`%myfiles%\b3sum.exe --check %cd%\dummyhash.blake3`

After that it checks files, and the end. Also, path part was quoted but doesn't work
`%myfiles%\b3sum.exe --check "%cd%\dummyhash.blake3"`

**Comment by oconnor663** [comment]
When I try something like `b3sum --check "%HOMEPATH%\checkfile"`, it seems to work fine for me, both in the terminal and in a .bat script. I'm not sure what could be going wrong here. Maybe you could give us a more complete example to reproduce the problem?

**Comment by ZeusMods** [comment]
Here is source code of batch self
https://paste.0xfc.de/?1cdc58912c26e135#5JXvRgyyYTHmyWo99sm67UeaREiYJHMCRY4qoHXMK8Ae

**Comment by oconnor663** [comment]
That script works for me when I put `b3sum.exe` and `dummyhash.blake3` in the right places. I don't think there's a quoting problem. Is it possible that you're getting one of the filepaths wrong?

**Comment by ZeusMods** [comment]
> Is it possible that you're getting one of the filepaths wrong?

No, the path simply was C:\Test Folder\

**Comment by ZeusMods** [comment]
Will close for now.
