### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by warycat** [BLAKE3-team/BLAKE3#149]
```
warning: c/blake3_sse2_x86-64_unix.S:1707:9: error: invalid operand for instruction
warning:         movd xmm3, rax
warning:         ^
warning: c/blake3_sse2_x86-64_unix.S:1920:9: error: invalid operand for instruction
warning:         movd xmm12, rax
warning:         ^

error: failed to run custom build command for `blake3 v0.3.7 (/Users/larry/Documents/BLAKE3)`

Caused by:
  process didn't exit successfully: `/Users/larry/Documents/BLAKE3/target/debug/build/blake3-f481339805823215/build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=CARGO_FEATURE_PURE
  TARGET = Some("x86_64-apple-darwin")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  cargo:rerun-if-env-changed=CARGO_FEATURE_PREFER_INTRINSICS
  cargo:rerun-if-env-changed=CARGO_FEATURE_PURE
  cargo:rustc-cfg=blake3_sse2_ffi
  cargo:rustc-cfg=blake3_sse41_ffi
  cargo:rustc-cfg=blake3_avx2_ffi
  TARGET = Some("x86_64-apple-darwin")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-arch" "x86_64" "-Wall" "-Wextra" "-std=c11" "-o" "/Users/larry/Documents/BLAKE3/target/debug/build/blake3-aa7029368e481445/out/c/blake3_sse2_x86-64_unix.o" "-c" "c/blake3_sse2_x86-64_unix.S"
  cargo:warning=c/blake3_sse2_x86-64_unix.S:1707:9: error: invalid operand for instruction
  cargo:warning=        movd xmm3, rax
  cargo:warning=        ^
  cargo:warning=c/blake3_sse2_x86-64_unix.S:1920:9: error: invalid operand for instruction
  cargo:warning=        movd xmm12, rax
  cargo:warning=        ^
  exit code: 1

  --- stderr


  error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-arch" "x86_64" "-Wall" "-Wextra" "-std=c11" "-o" "/Users/larry/Documents/BLAKE3/target/debug/build/blake3-aa7029368e481445/out/c/blake3_sse2_x86-64_unix.o" "-c" "c/blake3_sse2_x86-64_unix.S" with args "cc" did not execute successfully (status code exit code: 1).


warning: build failed, waiting for other jobs to finish...

```

**Comment by sneves** [comment]
Looks like an easy fix, though it's weird that this never came up before. What compiler is this?

**Comment by sneves** [comment]
Can you confirm that the latest master branch works?

**Comment by warycat** [comment]
Thank, it works now.

**Comment by oconnor663** [comment]
Should I go ahead and cut a release? Or do you think there might be more fixes like this one?

**Comment by sneves** [comment]
Dammit, my patch was actually overeager; the .asm files should have stayed unchanged. Pushed a fix just now.

I have no way to know if we've already exhausted all/most toolchain quirks like this. MOVD/MOVQ should, in theory, be interchangeable, but here we are.

Anyway, apart from that MSVC quirk where _only_ MOVD is accepted, all the other routines have MOVD/MOVQ consistent with operand size, so I don't know what problem there could be next.

**Comment by warycat** [comment]
Why is it implemented in asm in the first place? IMO machine code should be generated by compiler.

**Comment by elichai** [comment]
@warycat compilers aren't always great at producing fast mathematical operations in a tight hot loop.
especially vectorizing across multiple different bitwise/arithmetic operations.

in those instances it's common practice to implement ASM manually.

I hope in the future it could be converted to inline asm(when it's stable) which should solve some of the compatibility problems.

**Comment by oconnor663** [comment]
@warycat we do have intrinsics-based implementations as an alternative to hand-written assembly. If you'd like to compare the performance and build times of these, take a look at the `prefer_intrinsics` Cargo feature.

The fundamental question of "when are (some) humans better than an optimizing compiler" is pretty complicated. For the specific case of "SIMD optimizations for a hash function", I'd suggest two ideas:

1. Optimizing compilers aren't very good at figuring out "high-level" details about a program. It's not always clear what "high-level" and "low-level" mean exactly, but there are certain trends, and one important one is memory layout. When you say `struct Foo { int x; int y; int z; }` in C/C++, that fully determines the memory layout of that struct. Things in Rust are a little more flexible, but the compiler still has to follow rules like "an array of `Foo` is contiguous and each `Foo` in it is individually addressable". The compiler isn't usually allowed to transform e.g. an "array of structs" program into a "struct of arrays" program. (Though even if it was, it can be very difficult to automate a transformation like that.) Notably for our purposes here, SIMD optimizations are very closely related to memory layout. Optimizers are good at detecting cases where nearby arithmetic ops could be coalesced into a vector op, but if the operands aren't _already_ laid out in vectors, the compiler might have to emit an expensive gather/scatter that ends up making the whole thing slower than the scalar code was. To really take advantage of SIMD, the programmer needs to explicitly arrange their data in vectors up front. Given that the programmer already needs a plan in their head for what SIMD instructions are going to be generated, it's not too surprising that hand-writing those instructions is more effective for SIMD code than it is for generic application code.

2. Crypto primitives like hash functions and ciphers aren't designed in a vacuum. They aren't laws of nature that we have to figure out how to code. Rather, when we design these algorithms, we know in advance what instructions are fast and what instructions are slow, and we can make deliberate design choices to make sure we get to use the fast ones and avoid the slow ones. Given that, it's not too surprising that we have an easier time hand-writing those instructions than we would with generic application code.

**Comment by warycat** [comment]
> @warycat we do have intrinsics-based implementations as an alternative to hand-written assembly. If you'd like to compare the performance and build times of these, take a look at the `prefer_intrinsics` Cargo feature.
> 
> The fundamental question of "when are (some) humans better than an optimizing compiler" is pretty complicated. For the specific case of "SIMD optimizations for a hash function", I'd suggest two ideas:
> 
> 1. Optimizing compilers aren't very good at figuring out "high-level" details about a program. It's not always clear what "high-level" and "low-level" mean exactly, but there are certain trends, and one important one is memory layout. When you say `struct Foo { int x; int y; int z; }` in C/C++, that fully determines the memory layout of that struct. Things in Rust are a little more flexible, but the compiler still has to follow rules like "an array of `Foo` is contiguous and each `Foo` in it is individually addressable". The compiler isn't usually allowed to transform e.g. an "array of structs" program into a "struct of arrays" program. (Though even if it was, it can be very difficult to automate a transformation like that.) Notably for our purposes here, SIMD optimizations are very closely related to memory layout. Optimizers are good at detecting cases where nearby arithmetic ops could be coalesced into a vector op, but if the operands aren't _already_ laid out in vectors, the compiler might have to emit an expensive gather/scatter that ends up making the whole thing slower than the scalar code was. To really take advantage of SIMD, the programmer needs to explicitly arrange their data in vectors up front. Given that the programmer already needs a plan in their head for what SIMD instructions are going to be generated, it's not too surprising that hand-writing those instructions is more effective for SIMD code than it is for generic application code.
> 2. Crypto primitives like hash functions and ciphers aren't designed in a vacuum. They aren't laws of nature that we have to figure out how to code. Rather, when we design these algorithms, we know in advance what instructions are fast and what instructions are slow, and we can make deliberate design choices to make sure we get to use the fast ones and avoid the slow ones. Given that, it's not too surprising that we have an easier time hand-writing those instructions than we would with generic application code.

Thanks for the help. I can build this with the prefer_intrinsics flag.
