### ISSUE TITLE
Typo in test vector comment

### ISSUE THREAD

**Issue by riastradh** [BLAKE3-team/BLAKE3#15]
The comment in test_vectors.json says:

> For derive_key, the test input is used as the input key, and the context string is 'BLAKE3 2019-12-27 16:29:52 example context'.

https://github.com/BLAKE3-team/BLAKE3/blob/80260dc763086e371aed122eda97665b9dd48800/test_vectors/test_vectors.json#L2

However, the test vectors were actually computed with the context string `BLAKE3 2019-12-27 16:29:52 test vectors context`.  Citations:

https://github.com/BLAKE3-team/BLAKE3/blob/2fac7447e02aa0f532ebcacbfffc71565b691aea/test_vectors/src/lib.rs#L32
https://github.com/BLAKE3-team/BLAKE3/blob/2fac7447e02aa0f532ebcacbfffc71565b691aea/test_vectors/src/lib.rs#L93-L97

By following the source code rather than the comment, I am able to reproduce the test vectors with my independent implementation of BLAKE3.

**Comment by oconnor663** [comment]
UGGGH, I can't believe I messed this up. Thank you for catching it. Will update the comment immediately.
