### ISSUE TITLE
C reference implementation: BLAKE3_MAX_SIMD_DEGREE is unused

### ISSUE THREAD

**Issue by larryhastings** [BLAKE3-team/BLAKE3#152]
blake3.h defines `BLAKE3_MAX_SIMD_DEGREE`:

`#define BLAKE3_MAX_SIMD_DEGREE 16`

It then ignores it, and instead uses `MAX_SIMD_DEGREE`, defined in blake3_impl.h.

**Comment by oconnor663** [comment]
Ah thanks, I'll clean that up. I think that got missed in some refactoring early on.
