### ISSUE TITLE
non-test C implementation fails to build

### ISSUE THREAD

**Issue by adamdmoss** [BLAKE3-team/BLAKE3#16]
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

```
% make
gcc -O3 -Wall -Wextra -std=c11 -pedantic -c blake3_sse41.c -o blake3_sse41.o -msse4.1 -D BLAKE3_USE_SSE41
gcc -O3 -Wall -Wextra -std=c11 -pedantic -c blake3_avx2.c -o blake3_avx2.o -mavx2 -D BLAKE3_USE_SSE41 -D BLAKE3_USE_AVX2
gcc -O3 -Wall -Wextra -std=c11 -pedantic -c blake3_avx512.c -o blake3_avx512.o -mavx512f -mavx512vl -D BLAKE3_USE_SSE41 -D BLAKE3_USE_AVX2 -D BLAKE3_USE_AVX512
gcc -O3 -Wall -Wextra -std=c11 -pedantic blake3.c blake3_dispatch.c blake3_portable.c main.c blake3_sse41.o blake3_avx2.o blake3_avx512.o -o blake3
/tmp/ccJZjf2t.o: In function `main':
main.c:(.text.startup+0x1f9): undefined reference to `get_cpu_features'
main.c:(.text.startup+0x245): undefined reference to `g_cpu_features'
collect2: error: ld returned 1 exit status
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 1

```

Similar story with clang version 8.0.0-3~ubuntu18.04.2 (tags/RELEASE_800/final)

**Comment by dd4rk** [comment]
Simply `make` doesn't generate `-DBLAKE3_TESTING`, that causes `enum cpu_feature g_cpu_features` to be static.
Use `make test` or write your own test code instead.

**Comment by oconnor663** [comment]
Yes originally the bare `make` command would compile a working executable (pretty bare bones, mostly just for playing around). As part of adding dynamic feature detection, that build target broke. We need to fix it, of course, but we also need to substantially clean up the docs and CLI interface for that target. It's not yet clear exactly what we want it to be.

**Comment by oconnor663** [comment]
I'm going to close this, as `main.c` is only intended for testing at this point. The new `c/README.md` file has new instructions for building.
