### ISSUE TITLE
blake2+1.net is expiring

### ISSUE THREAD

**Issue by divinity76** [BLAKE3-team/BLAKE3#162]
blake2 has a dedicated domain at blake2.net , as far as i can tell, some jackass registered blake2+1.net just to show unrelated advertising on it, seems it'll expire in a couple of days (expired at 2021-01-09, currently in a "reactivation period" which should have expired like.. 20 days ago itself), 

if there's any interest in creating a blake2+1.net domain like blake2.net, now is probably a good time to look into that

**Comment by oconnor663** [comment]
We currently have blake3.io, which redirects to this repo. Maybe that's good enough?

**Comment by divinity76** [comment]
oh didn't know, that sounds good to me.
