### ISSUE TITLE
Question: Is it possible to have `digest` return 64 bytes?

### ISSUE THREAD

**Issue by FrankC01** [BLAKE3-team/BLAKE3#163]
We have a unique constraint for 512 bit return from `digest`... any possibility? alternatives?

**Comment by oconnor663** [comment]
Absolutely. With the `blake3` Rust crate, you do it like this:

```rust
let mut long_digest = [0; 64];
blake3::Hasher::new()
    .update(b"hello world\n")
    .finalize_xof()
    .fill(&mut long_digest);
```

And with the `b3sum` command line utility, you do it like this:

```
echo hello world | b3sum --length=64
```

But just to be clear, when you said "return from `digest`", what exactly did you mean? Were you referring to the the [Python bindings](https://pypi.org/project/blake3/) maybe?

**Comment by FrankC01** [comment]
Thanks! I was using `digest` synonymously with `hash`.

**Comment by oconnor663** [comment]
Got it. In Python there is actually a method called `digest`, to be consistent with how the Python standard library does hashing. It looks like this:

```
In [1]: from blake3 import blake3

In [2]: blake3(b"hello world\n").digest(length=64)
Out[2]: b'\xdcZN\xdb\x82@\xb0\x18\x12@R\xc30\'\x06\x96\xf9gq\xa6;E%\n\\\x17\xd3\x00\x0e\x823Ug]\xac\xfc>\xd1\xa0i6\xec\xae&\x97\xd6\xba\xea\xa5\xe4#\xc0\xef\xa5\x1dE\xb3"\xf3\xf2\xca.\xc0='
```

But yeah, all of our various APIs support this in some way, and hopefully most of the 3rd party ones do too. I'll go ahead and close this issue, but feel free to ask more questions here or open new ones.

**Comment by MarcusJohnson91** [comment]
Is there a way to use Blake3 as a hashlist, with 64 bit keys?

I know, that's really small compared to the normal 256/512 bit output, but...

**Comment by oconnor663** [comment]
@MarcusJohnson91 you can take any output size, including short outputs. (You can ask the library for a short output, or you can just truncate the default-length output. You get the same answer either way.) But when you do that, you have to pay careful attention to the security consequences. Below 256 bits you start to lose collision resistance, and below 128 bits you start to lose second-preimage resistance. If you don't need either of those things, it's possible you don't need a cryptographic hash at all, and you might find that some non-cryptographic hashes are faster than BLAKE3. But that depends a lot on your hardware and your input size, and sometimes they're not actually faster. If the performance difference matters to you, it's best to benchmark it yourself.

If you're doing something involving file integrity, you might also find [Bao](https://github.com/oconnor663/bao) interesting.
