### ISSUE TITLE
Comment and buffer size don't match

### ISSUE THREAD

**Issue by bronson** [BLAKE3-team/BLAKE3#167]
The comment says it's using a 64 KiB buffer but the code allocates a 256 KiB buffer.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/1776/115063873-04a86480-9ea1-11eb-9c02-f804041538a2.png">

Maybe the code should be `[u8; 65536]` or `['\0'; 65536]`?

Or leave it. It works fine as is!

Link to the code: https://github.com/BLAKE3-team/BLAKE3/blob/4b7babbe99c04bd573aad49db24484d07c574ae9/b3sum/src/main.rs#L261

**Comment by oconnor663** [comment]
Are you sure it's allocating 256 KiB? My reading of that code is that it's doing what it says. (Specifically, that the type of the array elements are inferred to be `u8` based on the call to `read()`.)

**Comment by bronson** [comment]
I'm wrong! Yesterday I instrumented your code (what I should have done first) and saw it actually IS 64KiB.

I filed the issue after writing a test program that shows it's 256KiB...  But I didn't realize Rust backpropagates type inference. It's 256KiB, until you pass it to a function that accepts byte arrays, whereupon Rust snaps it to the right size.

Sorry for the noise, closing...

**Comment by oconnor663** [comment]
Yeah the rule is that integer literals default to `i32` unless some other constraint is deduced. In production code, there's almost always some constraint, but in hello-world examples not always.
