### ISSUE TITLE
Please document collision-resistance properties of BLAKE3 with less than 256 bits

### ISSUE THREAD

**Issue by joshtriplett** [BLAKE3-team/BLAKE3#168]
I'm interested in the collision-resistance and safety of BLAKE3 with less than 256 bits (either via XOF or truncation), for use in applications storing a very large number of hash values and sensitive to storage size.

Would BLAKE3 with 224 bits be considered as safe as SHA-224, SHA-512/224, or SHA3-224? Is that likely to be reasonably safe for years to come?

Would any shorter number of bits be acceptably secure?

If so, what would be the preferred method of obtaining such hashes? XOF, or truncation?

Would those answers vary for other BLAKE-family hashes, which use a larger number of rounds?

(I entirely understand that hash length is a tradeoff. I'm trying to find an acceptable balance between degree of future-proofing and usability in storage-size-sensitive applications.)

**Comment by oconnor663** [comment]
Btw, if you happen to be working on tracking build artifacts, that's right up my alley. I was on the Buck team at Facebook back in the day, and a friend and I still maintain a tool called [`peru`](https://github.com/buildinspace/peru) that's kind of in the same space.

**Comment by sneves** [comment]
Any better-than-generic attack that works for n-t-bit output will also apply to the full n-bit output, as you're only giving the attacker more information to work with in that case.

**Comment by joshtriplett** [comment]
Thanks for the explanation!

Would you consider documenting those details somewhere in the BLAKE3 documentation? Most notably, that BLAKE3 at N bits is collision-resistant to N/2 bits, and that XOF and truncation are equivalent?

**Comment by oconnor663** [comment]
@joshtriplett I just opened https://github.com/BLAKE3-team/BLAKE3/pull/169 with some proposed doc changes. Let me know what you think.

**Comment by joshtriplett** [comment]
That looks great! Thank you very much.

**Comment by oconnor663** [comment]
Merged.
