### ISSUE TITLE
Error in (generated) blake3.h causes build to fail

### ISSUE THREAD

**Issue by chill1n** [BLAKE3-team/BLAKE3#174]
I'm building the blake3 libs (on x86_64 with Ubuntu20.04) using:
    cargo build --release
    cargo install cargo-c
    cargo install cargo-strip
    cargo strip
    sudo sh -c "export PATH=$HOME/.cargo/bin:$PATH && rustup default stable && cargo cinstall --release && strip /usr/local/lib/libblake3*"

My project build fails with:

/usr/local/include/blake3/blake3.h:25:24: error: redefinition of ‘const uintptr_t DEGREE’
   25 | static const uintptr_t DEGREE = 4;

This is due to the following lines in the generated target/x86_64-unknown-linux-gnu/release/blake3.h:
static const uintptr_t DEGREE = 8;

static const uintptr_t DEGREE = 4;

static const uintptr_t DEGREE = 4;

It's not clear to me what the source of these lines is, and what the proper value of DEGREE is supposed to be.

**Comment by oconnor663** [comment]
This looks like a bug in `cargo-c`. These `DEGREE` constants are private values in different submodules, which don't conflict with each other in Rust. But it looks like `cargo-c` is dumping them into the global namespace and making them conflict. Could you report this bug upstream?
