### ISSUE TITLE
Release to crates.io?

### ISSUE THREAD

**Issue by kornelski** [BLAKE3-team/BLAKE3#179]
I wanted to update dependencies. I've noticed that version in git has them already updated, it's just not released yet.

**Comment by oconnor663** [comment]
The [next release will be 1.0](https://github.com/BLAKE3-team/BLAKE3/pull/173). I've been holding off on pushing the button until I have time to really sit down and make sure everything's in order. Life events have been intervening though: I got married this Saturday :)

**Comment by kornelski** [comment]
Congrats!

But please don't wait for 1.0. There are crates depending on 0.3. The current version needs a release.
