### ISSUE TITLE
Allow b3sum to output raw

### ISSUE THREAD

**Issue by tom-adsfund** [BLAKE3-team/BLAKE3#18]
Please could you provide the option to output the hash as the raw bytes?

**Comment by oconnor663** [comment]
This sounds like a good idea. Probably it would be an error if you supplied more than one argument in this case? Could you tell me more about your use case?

**Comment by tom-adsfund** [comment]
The idea is that I want to create a large hash and save that to a file, and yet don't want to keep it in hex format. I don't really want to go into any extra details!

**Comment by phayes** [comment]
I've added PR #22 to resolve this issue.  

Raw output is super useful.  I've found myself needing it for piping the raw digest over to another process like openssl for signing.

**Comment by oconnor663** [comment]
Thank you! Commented on the PR.

**Comment by Trendsetter74** [comment]
I wish I knew more about what's going on but I'm very simple person just
need to learn how to code

Kenneth Smith
