### ISSUE TITLE
Make BLAKE3 compile on Freebsd 

### ISSUE THREAD

**Issue by riktam** [BLAKE3-team/BLAKE3#182]
Make BLAKE3 compile on Freebsd

**Comment by oconnor663** [comment]
Do you have any specific errors you're running into?

**Comment by fcorbelli** [comment]
Just for info: BLAKE3 (C) DOES compile on FreeBSD in "straight-plain-C" by stripping everything (no SSE, asm etc).  
Is it  interesting that I put the source ?

**Comment by riktam** [comment]
That would be great!

**Comment by fcorbelli** [comment]
Here it is
https://github.com/fcorbelli/zpaqfranz

**Comment by fcorbelli** [comment]
A smaller version here
https://github.com/fcorbelli/sblake/tree/main

**Comment by cross** [comment]
I'm also working today to get blake3 building on FreeBSD.  A build of another program that links to libblake3.a fails with lots of undefined symbols referenced by blake3_dispatch.c:
`ld: error: undefined symbol: blake3_hash_many_sse2
>>> referenced by blake3_dispatch.c
>>>               blake3_dispatch.c.o:(blake3_hash_many) in archive 
libblake3.a`
(and many others)

From above conversation I can see that I could figure out how to build it without support for any of those, but I assume the effort to make it build with them (FreeBSD 13 on x86_64, using clang) wouldn't be hard, I assume it's just some settings needed.  Let me know if I can help test things.

**Comment by oconnor663** [comment]
A lot of this (for example "how to skip building SSE2 etc. on x86") is documented here: https://github.com/BLAKE3-team/BLAKE3/tree/master/c#building

**Comment by cross** [comment]
Yeah, and I'm able to build the example by listing all the .S files.  I think my problem is that the building of the .a didn't include those.  But looking more, I don't know that BLAKE3 is supplying builds of the C library.  Just the sources.  In which case, it's the application pulling that in and building the .a file that's the issue.
Am I correct that blake3 sources, as distributed, don't build a C library?

**Comment by fcorbelli** [comment]
The questions are

1) do you want a straight C++ (no asm)? Some fixing is needed for incompatible C vs C++, you can find here https://github.com/fcorbelli/sblake/tree/main
I use it all the time into FreeBSD archiver

2) do you want C++ WITH asm on FreeBSD for x64 architecture? I done this too (but with a reworked source, only one .S). Not very useful for BSD (that compile just about everything, not only Intel-compatible), so I use only on Win64 (with different single-file .S file)

**Comment by sneves** [comment]
Static libraries are not covered by the readme, but can be produced as follows:
```
$(CC) $(CFLAGS) -c blake3.c -o blake3.o
$(CC) $(CFLAGS) -c blake3_dispatch.c -o blake3_dispatch.o
$(CC) $(CFLAGS) -c blake3_portable.c -o blake3_portable.o
$(CC) $(CFLAGS) -c blake3_sse2_x86-64_unix.S -o blake3_sse2_x86-64_unix.o
$(CC) $(CFLAGS) -c blake3_sse41_x86-64_unix.S -o blake3_sse41_x86-64_unix.o
$(CC) $(CFLAGS) -c blake3_avx2_x86-64_unix.S -o blake3_avx2_x86-64_unix.o
$(CC) $(CFLAGS) -c blake3_avx512_x86-64_unix.S -o blake3_avx512_x86-64_unix.o
$(CC) $(CFLAGS) 
ar -rv libblake3.a blake3.o blake3_dispatch.o blake3_sse2_x86-64_unix.o blake3_sse41_x86-64_unix.o blake3_avx2_x86-64_unix.o blake3_avx512_x86-64_unix.o
```
Replace `$(CC) $(CFLAGS)` by your preferred compiler flags.

**Comment by BurningEnlightenment** [comment]
Thank you very much for your feedback. I am therefore closing this issue now. If there are any other more specific issues, please feel free to open a new issue.
