### ISSUE TITLE
Dangerous warnings reported: memory overflow?

### ISSUE THREAD

**Issue by fcorbelli** [BLAKE3-team/BLAKE3#183]
I am trying to port BLAKE3 to other systems, especially FreeBSD, as a single file (no include, no assembler, no nothing).   

I prepared a single source (which I attach as text) rather trivial, in which I removed (I hope) all the CPU-specific instructions.

When I compile it on Windows (gcc 7.3.0) I get two pretty bad warnings
```
C:\BLAKE3-master\c>fai
In function 'compress_parents_parallel',
    inlined from 'compress_subtree_to_parent_node' at example.c:587:13,
    inlined from 'blake3_hasher_update.part.0' at example.c:772:7:
example.c:476:5: warning: 'memcpy' writing 32 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
     memcpy(&out[parents_array_len * BLAKE3_OUT_LEN],
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            &child_chaining_values[2 * parents_array_len * BLAKE3_OUT_LEN],
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            BLAKE3_OUT_LEN);
            ~~~~~~~~~~~~~~~
example.c:476:5: warning: 'memcpy' writing 32 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
In function 'compress_subtree_to_parent_node',
    inlined from 'blake3_hasher_update.part.0' at example.c:772:7:
example.c:589:5: warning: 'memcpy' writing 96 bytes into a region of size 64 overflows the destination [-Wstringop-overflow=]
     memcpy(cv_array, out_array, num_cvs * BLAKE3_OUT_LEN);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

Any ideas?
Thank you

[example.txt](https://github.com/BLAKE3-team/BLAKE3/files/6878248/example.txt)

**Comment by oconnor663** [comment]
I've seen these warnings before, for example at https://github.com/ccache/ccache/issues/820. It seems to come up on older compiler versions or obscure platforms, though I'm not sure exactly why. Just now I tried to reproduce it with the file you linked inside a `gcc:7.3` Docker container, but I wasn't able to produce the warning. Should I try any particular compiler flags other than `-Wall -pedantic`?

**Comment by fcorbelli** [comment]
This is a Windows gcc 7.3.0, compiled by 
```
gcc -O3 -o ex.exe example.c  
```
No other flags needed

Same things on FreeBSD (gcc 7.3.0)
[freebsd_gcc_9_3_0.txt](https://github.com/BLAKE3-team/BLAKE3/files/6885099/freebsd_gcc_9_3_0.txt)

And on FreeBSD (gcc 9.3.0)
[bsd.txt](https://github.com/BLAKE3-team/BLAKE3/files/6885086/bsd.txt)

Maybe a bug in the compiler, but I suggest do "rework" those lines (to make the same things without warning).
It is common to have to make unnecessary changes to the sources to avoid warnings

**Comment by oconnor663** [comment]
https://github.com/BLAKE3-team/BLAKE3/issues/189 has a repro of these warnings on Arch Linux.

**Comment by oconnor663** [comment]
I believe this is fixed by https://github.com/BLAKE3-team/BLAKE3/commit/b8e2dda186c69cece5412f8571bfabf14fd3d7ab, but please reopen if I've missed something.
