### ISSUE TITLE
Big File sometimes Prints out different Hashes?

### ISSUE THREAD

**Issue by CaptainCoward** [BLAKE3-team/BLAKE3#196]
When i try to print out the Blake 3 Hash of  some big .iso file (100GB) i would sometimes get a "wrong" hash. Any clue what's the reason?  Could it be Windows-Defender realtime protection causing it?
I'm running the B3sum Utility 1.0.0
Windows 10 x64.

**Comment by oconnor663** [comment]
If this is a BLAKE3 bug it would be extremely serious! Hopefully the explanation is something simpler. Any chance some other process is editing the file while you hash it? If you have time, there are many things I'd like to try:

- Can you repro the issue with any other hash function?
- Is there any difference between hashing the file directly by name vs using `<` to read it through stdin?
- Does `--num-threads=1` or `--no-mmap` make a difference?
- Is the "wrong" hash always the same, or is there a variety of wrong hashes?

I'd love to get my hands on this file if all possible. What do you think would be the easiest way to transfer it? I could give you SSH access to a server to rsync it maybe? If you'd like to go that route, could you give me your SSH public key?

**Comment by oconnor663** [comment]
In fact, I probably don't need the file itself. It's probably good enough to know its exact size in bytes. Could you tell me its exact size?

**Comment by CaptainCoward** [comment]
I'm really sorry but this was a false Alert. The reason was defective RAM. I tested the RAM with Memtest and it would print out Tons of errors. I'm actually glad that Blake pointed out the issue, otherwise i would maybe go on with that bad Stick for Months risking losing lots of important work.

**Comment by oconnor663** [comment]
No worries, thanks for following up!
