### ISSUE TITLE
Python and/or JS implementations

### ISSUE THREAD

**Issue by DonaldTsang** [BLAKE3-team/BLAKE3#20]
This might be a good idea for educational purposes.

**Comment by oconnor663** [comment]
@connor4312 has put up some WASM bindings: https://github.com/connor4312/blake3 (third-party code, use at your own risk)

Looks like there's some Python discussion happening here: https://bugs.python.org/issue39298. I will chime in later today.

**Comment by DonaldTsang** [comment]
Yay looks like Python will support native BLAKE3 and KangarooTwelve!
But I did hope for a pure Python implementation that allows for easy explaining of BLAKE3 though.

**Comment by oconnor663** [comment]
Maybe! So far this is just one person's proposal. But it does make me excited :)

There is a pure Python implementation of BLAKE3 here, as part of the pure Python implementation of Bao: https://github.com/oconnor663/bao/blob/master/tests/bao.py. The Bao-specific parts could be removed, if we wanted to adapt it into just a BLAKE3 example implementation. It also uses an older (but equivalent) version of the tree algorithm, and I should probably bring it up to speed with what we recommend in Section 5.1.2 of the BLAKE3 spec.

**Comment by connor4312** [comment]
Yea, the wasm build for JS should work for general use. I also started on some native neon-based bindings which make it more performant for consumers who can use them. A pure-JS implementation would be interesting for educational purposes, but there's probably not any practical benefit for using it over the wasm bindings.

**Comment by oconnor663** [comment]
Closing this for now to keep the issue queue clean.

**Comment by DonaldTsang** [comment]
@oconnor663 please add that implementation as a note on ReadME, good to know that it exists.
