### ISSUE TITLE
b3sum crate missing Cargo.lock

### ISSUE THREAD

**Issue by tuesdaycodes** [BLAKE3-team/BLAKE3#210]
trying to make an os package for b3sum and the Cargo.lock is missing causing failures. can it be added please?

official docs suggest the lock should be included in version control for binaries
https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

**Comment by oconnor663** [comment]
There is a `Cargo.lock` file created automatically when we publish releases to crates.io. If you like you can fetch it with:

    curl -L https://crates.io/api/v1/crates/b3sum/1.2.0/download | tar xz "b3sum-1.2.0/Cargo.lock" --to-stdout

Alternatively, you can build your own lockfile at packaging time, using `cargo generate-lockfile` or similar. Would one of these approaches work for you?

**Comment by tuesdaycodes** [comment]
the package i am working on doesnt have the ability to fetch from crates.io oddly. i might be able to temporarily work around with a prebuild step, but ideally the repo would have the lock file to make things smoother. i can try my work around and report back in the interim though might take a bit to get fully tested.

**Comment by oconnor663** [comment]
We could create one, but then I'd want to keep it updated at all times, which would be kind of annoying to maintain. `b3sum` is a pretty simple application as far as its dependency tree goes, and I don't expect to run into many build breaks over time, so the actual value of a committed lockfile is low. But maybe you could tell me more about the packaging system you're working with? If this is a common requirement for many different packaging systems, maybe I should just make everyone's lives eaiser and include it upstream...

**Comment by tuesdaycodes** [comment]
the official rust docs say the lock should be in version control. im working on openbsd right now, though same requirement is likely true for freebsd. having the lockfile will also help distros like debian, fedora, and arch for their reproducible builds. same reasoning for people building from source.

really you only need to update it in the repo when tagging a release, not all the time.

**Comment by tuesdaycodes** [comment]
@oconnor663 any update on getting the lockfile added to the repo?

**Comment by oconnor663** [comment]
Thank you for reminding me about this. When I'm generating the `Cargo.lock` file myself, is there a flag that says "ignore `path` dependencies (the `blake3` crate in the parent dir) and act like I'm getting everything from crates.io"? I noticed that the default lockfile doesn't include a package hash for blake3, but I'm not sure if anyone actually cares about this.

**Comment by tuesdaycodes** [comment]
you can specify that in your Cargo.toml. if found it will use the path, otherwise it goes to crates.io. 

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies

**Comment by oconnor663** [comment]
Yes that's what we [currently do](https://github.com/BLAKE3-team/BLAKE3/blob/da4c792d8094f35c05c41c9aeb5dfe4aa67ca1ac/b3sum/Cargo.toml#L18). But I notice that when I use e.g. `cargo build` to generate a lockfile, the entry for `blake3` looks like this:

```toml
[[package]]
name = "blake3"
version = "1.2.0"
dependencies = [
 "arrayref",
 "arrayvec",
 "cc",
 "cfg-if",
 "constant_time_eq",
 "digest",
 "rayon",
]
```

On the other hand, the entry in the lockfile on crates.io looks like this:

```toml
[[package]]
name = "blake3"
version = "1.2.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "526c210b4520e416420759af363083471656e819a75e831b8d2c9d5a584f2413"
dependencies = [
 "arrayref",
 "arrayvec",
 "cc",
 "cfg-if",
 "constant_time_eq",
 "digest",
 "rayon",
]
```

It seems like if we're going through the trouble of publishing a lockfile, we should make sure it actually locks all the dependencies. But the only way I can figure out how to do this locally is to run `cargo publish --dry-run` and fish the lockfile out of build artifacts. That makes me wonder whether I'm fighting the system here, or maybe just missing some obvious flag.

**Comment by oconnor663** [comment]
In fact, if I copy that build artifact to `b3sum/Cargo.lock`, I have a problem, because regular build commands will overwrite it and delete those `source` and `checksum` entries. And of course I don't want the regular build commands to dirty the repo.

**Comment by tuesdaycodes** [comment]
im not sure the resulting binary/lib itself can really record a hash see https://github.com/rust-lang/rfcs/pull/3127 for a limitation on rust compiler itself. even then so long as most things get recorded its probably fine as a start

**Comment by oconnor663** [comment]
Just pushed the lockfile. If I forget to bump it during a release, please remind me :)
