### ISSUE TITLE
Question: How asm is generated?

### ISSUE THREAD

**Issue by vt-alt** [BLAKE3-team/BLAKE3#214]
I'm curious how your assembly code is generated?

Excuse me, if I am mistaken and it's manually coded. I thought it's generated, because - no `.S` files have header unlike `.c`; a lot of indexing by numbers (and not symbolic); some labels reference the same location; and not readable formatting like in example below.

```
        vmovups xmm8, xmmword ptr [r8+rdx-0x40]
        vinsertf128 ymm8, ymm8, xmmword ptr [r12+rdx-0x40], 0x01
        vmovups xmm9, xmmword ptr [r9+rdx-0x40]
        vinsertf128 ymm9, ymm9, xmmword ptr [r13+rdx-0x40], 0x01
        vunpcklpd ymm12, ymm8, ymm9
        vunpckhpd ymm13, ymm8, ymm9
        vmovups xmm10, xmmword ptr [r10+rdx-0x40]
        vinsertf128 ymm10, ymm10, xmmword ptr [r14+rdx-0x40], 0x01
        vmovups xmm11, xmmword ptr [r11+rdx-0x40]
        vinsertf128 ymm11, ymm11, xmmword ptr [r15+rdx-0x40], 0x01
        vunpcklpd ymm14, ymm10, ymm11
        vunpckhpd ymm15, ymm10, ymm11
```

**Comment by sneves** [comment]
A bit of both. The code was written manually, but to support two different syntaxes and calling conventions there is some macro machinery used to generate the final result. Hence the somewhat artificial look with the labels and offsets.

**Comment by vt-alt** [comment]
Ah thanks for the info! (I thought maybe something like [ispc](https://ispc.github.io/) is used.)
