### ISSUE TITLE
MSVC warnings at levels 3 and 4

### ISSUE THREAD

**Issue by zao** [BLAKE3-team/BLAKE3#218]
Visual Studio 2022 Preview (v17.1.0-pre.2.0) building BLAKE3 1.3.0 for x64 emits the following narrowing warnings with warning level /W3:

```
S:\BLAKE3\c\blake3_avx512.c(1050): warning C4244: 'function': conversion from 'uint64_t' to 'int', possible loss of data
S:\BLAKE3\c\blake3_avx2.c(222): warning C4244: 'function': conversion from 'uint64_t' to 'int', possible loss of data
S:\BLAKE3\c\blake3_sse41.c(445): warning C4244: 'function': conversion from 'uint64_t' to 'int', possible loss of data
S:\BLAKE3\c\blake3_sse2.c(451): warning C4244: 'function': conversion from 'uint64_t' to 'int', possible loss of data
```

They are from passing `uint64_t counter` to intrinsics `_mm512_set1_epi32`, `_mm256_set1_epi32`, `_mm_set1_epi32`, `_mm_set1_epi32` which are prototyped to take an `int`.

While probably harmless it raises concerns for a reader like me that there might be something subtly off deep inside the vendored library as it pops up as part of my project build.

Some additional warnings manifest at /W4:
```
S:\BLAKE3\c\blake3_avx512.c(471): warning C4057: 'function': 'const char *' differs in indirection to slightly different base types from 'const uint8_t *'
S:\BLAKE3\c\blake3_avx512.c(727): warning C4057: 'function': 'const char *' differs in indirection to slightly different base types from 'const uint8_t *'
S:\BLAKE3\c\blake3_avx512.c(1040): warning C4057: 'function': 'const char *' differs in indirection to slightly different base types from 'const uint8_t *'
S:\BLAKE3\c\blake3_avx2.c(211): warning C4057: 'function': 'const char *' differs in indirection to slightly different base types from 'const uint8_t *'
S:\BLAKE3\c\blake3_sse41.c(432): warning C4057: 'function': 'const char *' differs in indirection to slightly different base types from 'const uint8_t *'
S:\BLAKE3\c\blake3_sse2.c(83): warning C4244: 'function': conversion from 'const int' to 'short', possible loss of data
S:\BLAKE3\c\blake3_sse2.c(438): warning C4057: 'function': 'const char *' differs in indirection to slightly different base types from 'const uint8_t *'
```
These are all from calls to `_mm_prefetch` and `_mm_set1_epi16`, which has prototypes taking `char const*` and `short` correspondingly.

**Comment by oconnor663** [comment]
The coversions from `uint64_t` to `int` are indeed intending to truncate (the other half of the int gets handled on a nearby line), but we can make those casts explicit to silence the warnings. Will look at the others shortly.

**Comment by zao** [comment]
I can verify that the PR resolves my warnings.

**Comment by oconnor663** [comment]
@sneves I've also noticed the following when building in 32-bit mode on Windows. What do you think is the cleanest way to fix it? (Given that the function claims to handle a `uint64_t`, it seems like kind of a bug, though in practice we only call it with a `size_t`.)

```
D:\a\blake3-py\blake3-py\c_impl\vendor\blake3_impl.h(103): warning C4244: 'function': conversion from 'uint64_t' to 'unsigned long', possible loss of data
```

**Comment by sneves** [comment]
Yeah that's just the same kind of thing, I forgot about 32-bit conversions.

```diff
diff --git a/c/blake3_impl.h b/c/blake3_impl.h
index ba2e91c..cc5672f 100644
--- a/c/blake3_impl.h
+++ b/c/blake3_impl.h
@@ -96,11 +96,11 @@ static unsigned int highest_one(uint64_t x) {
 #elif defined(_MSC_VER) && defined(IS_X86_32)
   if(x >> 32) {
     unsigned long index;
-    _BitScanReverse(&index, x >> 32);
+    _BitScanReverse(&index, (unsigned long)(x >> 32));
     return 32 + index;
   } else {
     unsigned long index;
-    _BitScanReverse(&index, x);
+    _BitScanReverse(&index, (unsigned long)x);
     return index;
   }
 #else
```

There are also a couple of cases in blake3.c where `round_down_to_power_of_2` is called with `size_t` input but the result is nominally `uint64_t` and might result in warnings when assigned back to `size_t`. No bugs, though.
