### ISSUE TITLE
Noob question how to run the binary in windows

### ISSUE THREAD

**Issue by rock4t2** [BLAKE3-team/BLAKE3#221]
I have downloaded the .exe file for windows and put it in the folder which contains the file that I want to find the blake3 hash. But upon running the exe file and putting the command line parameter "b3sum -c [filename]", I don't get any thing. I am very new to these things, any help is appreciated..

**Comment by oconnor663** [comment]
For just hashing a file, you don't want the `-c` argument. Maybe you got it from [this example](https://github.com/BLAKE3-team/BLAKE3#the-b3sum-utility)? But note that there it's an argument to `head`, not to `b3sum`.
