### ISSUE TITLE
RUSTSEC-2020-0077

### ISSUE THREAD

**Issue by strangelittlemonkey** [BLAKE3-team/BLAKE3#236]
[memmap](https://rustsec.org/packages/memmap.html) is unmaintained

Issued
    December 2, 2020 
Package
    memmap ([crates.io](https://crates.io/crates/memmap)) 
Type
    INFO Unmaintained 
Details
    https://github.com/danburkert/memmap-rs/issues/90 
Patched
    no patched versions 
Unaffected

        >0.7.0

Description

The author of the memmap crate is unresponsive.

Maintained alternatives:

    [mapr](https://github.com/filecoin-project/mapr)
    [memmap2](https://github.com/RazrFalcon/memmap2-rs)

**Comment by oconnor663** [comment]
Thanks!
