### ISSUE TITLE
`b3sum --raw` should work like `b3sum` without `raw`

### ISSUE THREAD

**Issue by Rudxain** [BLAKE3-team/BLAKE3#250]
There's no need to throw an error, or silently ignore files, since every hash in the output will have **exactly** the same fixed size. So even though different checkfiles may have different hash lengths, each one has a fixed "shared" length. This means `--check` can work on checkfiles generated by `--raw`. To avoid implicit guessing, the user must use `b3sum --raw --check` to explicitly tell the program to consume a binary checkfile.

Please let me know if I'm missing something (like obstacles to implement this, or anything else I didn't take into account)

**Comment by oconnor663** [comment]
I'm having trouble understanding what this issue is about. It sounds like it's about the interaction of `--raw` and `--check`, but there's no mention of `--check` in the title. Could you re-title it?

The biggest reason you can't use `--raw` with `--check` is that `--raw` implies `--no-names`, and we can't check anything without knowing the filenames we're supposed to check.

**Comment by Rudxain** [comment]
> I'm having trouble understanding what this issue is about. It sounds like it's about the interaction of `--raw` and `--check`, but there's no mention of `--check` in the title. Could you re-title it?

`--check` is a secondary thing, that's why I didn't include it in the title. I'm just suggesting that (at least) `--raw` should have more "parity" with the standard mode. `b3sum` doesn't need to support binary checkfiles, but it would be nice just for the sake of completeness (although that may be feature-creep, so I wouldn't recommend it).
 
> The biggest reason you can't use `--raw` with `--check` is that `--raw` implies `--no-names`, and we can't check anything without knowing the filenames we're supposed to check.

But what if `--no-names` was a default that could be overriden? Then the output would contain filenames (only if explicitly specified). But then the problem of filenames with special characters would get harder to solve... now I realize it's very likely a bad idea (for checkfiles).

However, a potential use-case of `--raw` with multiple files (with `--no-names` still implied) would be to create a file containing multiple hashes, then hash that binary file to get a smaller hash of all the previous files, that's related to #171.

Another use-case is to use files as "seeds" and use `b3sum` as a PRBG (Pseudo-Random Byte Generator). But having multiple seed for a single RNG seems like a very rare use-case, so I don't think it's "valid enough"

**Comment by Rudxain** [comment]
As explained in [this commit](https://github.com/Rudxain/xorsum/commit/c76a479247d2d60050f2f007f7dbe09481ffbee9), I now think (personally and subjectively) that this is not important.

(the following is said to "the team" (nobody in particular)) Please use available time to work on more important stuff! ignore this issue (for now), until an actual need "pops-up" in the future
