### ISSUE TITLE
b3sum pathologically slow in cygwin

### ISSUE THREAD

**Issue by elandorr** [BLAKE3-team/BLAKE3#254]
I was looking to replace sha1 with b3 for potentially lower resource usage for large datasets/many files. (As speed doesn't really matter - sha1 is already far above even all SSD limits for the non-millionaire population.)

On linux it runs fine, but in cygwin it's so slow, I killed the benchmark before it even finished. Don't need fancy loops to see this is broken:

```
Benchmark 1: nice -n -20 sh -c "dd if=/dev/urandom bs=1M count=1024 | sha1sum"
  Time (mean ± σ):      2.234 s ±  0.021 s    [User: 2.328 s, System: 0.362 s]
  Range (min … max):    2.192 s …  2.281 s    50 runs

Benchmark 2: nice -n -20 sh -c "dd if=/dev/urandom bs=1M count=1024 | b3sum"
 | Current estimate: 73.821 s █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ ETA 01:00:18
```

urandom to bypass the disk

To be useful in real life, the hashsum tool must work reliably from a toaster to cygwin and beyond, so I'm bringing it to your attention. sha1 and all the other typical ones work fine, so there is something b3 specific going on. I'm glad I discovered this bug before switching thousands of files. Imagine finding out it would take a thousand years when you need it in prod..

Here's one more *killer* bug-'feature' for you: Sometimes, just rarely, b3 works fine too, and is very fast. It's not related to caching since urandom works fine on windows and doesn't block. Absolutely no clue why it behaves so weirdly, when all the others work fine using the same methods/files.

I did not test in cmd/powershell as those are torture to deal with. A plain 'b3sum file' in cmd however seemed fast, but with this inconsistent behaviour that's not useful data. (Plus, no sane guy would write powershell madness, even if it somehow worked there, that's not an option.)

For comparison, here on a debian stable with the latest b3sum 1.3.1:
Not remotely as fast as the benchs of the lib itself from your frontpage, but not broken like windows:

```
Benchmark 1: nice -n -20 sh -c "dd if=/dev/urandom bs=1M count=1024 | sha1sum"
  Time (mean ± σ):      6.066 s ±  0.175 s    [User: 2.307 s, System: 4.066 s]
  Range (min … max):    5.782 s …  6.480 s    50 runs

Benchmark 2: nice -n -20 sh -c "dd if=/dev/urandom bs=1M count=1024 | b3sum"
  Time (mean ± σ):      4.234 s ±  0.117 s    [User: 0.382 s, System: 3.921 s]
  Range (min … max):    4.030 s …  4.572 s    50 runs

Summary
  'nice -n -20 sh -c "dd if=/dev/urandom bs=1M count=1024 | b3sum"' ran
    1.43 ± 0.06 times faster than 'nice -n -20 sh -c "dd if=/dev/urandom bs=1M count=1024 | sha1sum"'
```

Hope this helps, cheers

**Comment by elichai** [comment]
This also benchmarks cygwin's implementation of `/dev/urandom` which might be much slower than blake3,
maybe try reading from `/dev/null` or write data into a RAM mapped file and use that

**Comment by elandorr** [comment]
**urandom** is surprisingly much faster on cygwin than any linux box I have access to, so that can't be the cause:

linux: 
```
dd if=/dev/urandom of=/dev/null bs=1M count=4096
4096+0 records in
4096+0 records out
4294967296 bytes (4.3 GB, 4.0 GiB) copied, 14.0746 s, 305 MB/s
```

cygwin:
```
4294967296 bytes (4.3 GB, 4.0 GiB) copied, 1.29095 s, 3.3 GB/s
```

And why would it being slower than b3 result in b3 being 100x slower than sha1? At worst it should simply be identical i.e. limited by the input, shouldn't it?

**/dev/null**: Both are identical at presumably the time it takes to spawn the subshell plus a few ms. I suppose hashing algos react differently to all null so that doesn't show anything.

On a **ramdisk** it responds as expected:
```
Benchmark 1: nice -n -20 sh -c "sha1sum tails-amd64-5.3.1.iso"
  Time (mean ± σ):      2.529 s ±  0.047 s    [User: 2.255 s, System: 0.244 s]
  Range (min … max):    2.474 s …  2.729 s    50 runs

Benchmark 2: nice -n -20 sh -c "b3sum tails-amd64-5.3.1.iso"
  Time (mean ± σ):     301.7 ms ±  20.1 ms    [User: 872.5 ms, System: 866.6 ms]
  Range (min … max):   260.6 ms … 359.9 ms    50 runs

Summary
  'nice -n -20 sh -c "b3sum tails-amd64-5.3.1.iso"' ran
    8.38 ± 0.58 times faster than 'nice -n -20 sh -c "sha1sum tails-amd64-5.3.1.iso"'
```

**Plain file from an SSD**:

Given I did a whopping 50 runs, possible caching would affect both tests equally, so it's still useful for comparing:

```
Benchmark 1: nice -n -20 sh -c "sha1sum tails-amd64-5.3.1.iso"
  Time (mean ± σ):      2.708 s ±  0.627 s    [User: 2.316 s, System: 0.288 s]
  Range (min … max):    2.536 s …  6.991 s    50 runs

Benchmark 2: nice -n -20 sh -c "b3sum tails-amd64-5.3.1.iso"
  Time (mean ± σ):     13.832 s ±  1.907 s    [User: 0.707 s, System: 1.312 s]
  Range (min … max):   12.765 s … 26.264 s    50 runs

Summary
  'nice -n -20 sh -c "sha1sum tails-amd64-5.3.1.iso"' ran
    5.11 ± 1.38 times faster than 'nice -n -20 sh -c "b3sum tails-amd64-5.3.1.iso"'
```

Much slower than sha1. And it seems to have a good day. Yesterday I did what you would do as a user, i.e. go and hash some (varied) files, and that was 100x slower than sha1, ergo unusable. What sha1 finished in 10s b3 did in 10mins.

No problems with any other hashsum tool.

I don't have much time, but I made some more proper benchmarks of a typical real life use case for your information. The b3sum took forever, but I let it run cleanly until it finished.

In fact b3sum performed far worse than you can even imagine: all the others are single-threaded, b3sum raped 12 threads for a long time with worse results.

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `nice -n -20 sh -c "xxhsum tails-amd64-5.3.1.iso"` | 444.5 ± 16.1 | 403.6 | 470.0 | 1.14 ± 0.06 |
| `nice -n -20 sh -c "xxhsum -H3 tails-amd64-5.3.1.iso"` | 390.4 ± 13.7 | 354.6 | 415.8 | 1.00 |
| `nice -n -20 sh -c "b2sum tails-amd64-5.3.1.iso"` | 1806.3 ± 20.2 | 1768.0 | 1855.9 | 4.63 ± 0.17 |
| `nice -n -20 sh -c "md5sum tails-amd64-5.3.1.iso"` | 2135.6 ± 141.7 | 2049.7 | 2672.2 | 5.47 ± 0.41 |
| `nice -n -20 sh -c "sha1sum tails-amd64-5.3.1.iso"` | 2565.3 ± 33.6 | 2518.2 | 2719.2 | 6.57 ± 0.25 |
| `nice -n -20 sh -c "b3sum tails-amd64-5.3.1.iso"` | 13376.8 ± 648.5 | 12668.6 | 14359.9 | 34.27 ± 2.05 |

So I wondered if the threading implementation is what fails:

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `nice -n -20 sh -c "b3sum --num-threads 1 tails-amd64-5.3.1.iso"` | 5.367 ± 0.229 | 4.842 | 5.794 | 1.00 |
| `nice -n -20 sh -c "b3sum tails-amd64-5.3.1.iso"` | 13.274 ± 0.633 | 12.650 | 14.544 | 2.47 ± 0.16 |

b3sum clearly has problems with reading data. Multi-threading just makes it worse.

Some more interesting and hopefully useful observations:

b3sum has huge problems with pipes. I found xxhsum does too:
These two never finish (or if they do, I am not waiting more than a quarter of an hour):

`cat tails-amd64-5.3.1.iso | b3sum`
`cat tails-amd64-5.3.1.iso | xxhsum`

meanwhile

`cat tails-amd64-5.3.1.iso | sha1sum.exe`
`cat tails-amd64-5.3.1.iso | b2sum.exe`

work just fine.

In any case this is good information, and a good reason to stick with sha1sum or even md5sum. It works everywhere, with anything. You don't want to find out pipes are broken and speeds like a snail after you deployed it for millions of files.

Good luck!

**Comment by oconnor663** [comment]
@elandorr please don't use "rape" as a metaphor or anything remotely similar.

Normally

**Comment by elandorr** [comment]
I reject your pointless censorship to the fullest and will let you in on a little secret: I was abused as a child. But do I play Zeitgeist thought-police? No, of course I don't. This is not 'foul language' in the slightest. It's a common metaphor, and even I, who was actually abused, haven't even thought of any bad associations before you brought it up. It's a word like any other.

If you mind fetching a dictionary you can even see how it fits perfectly to the context:

> 2. The act of seizing and carrying off by force
> 3. The act of pillaging or plundering

A perfectly fine English word for using all threads at 100%.

Thank you very much for bringing it up. I love to be reminded of it. Sure worth the virtue signaling ego push. Although words are just words. We read many thousands a day. At least I do.

Besides, as a presumably mathematically minded person writing hashing algos, one should realize witch-hunting normal words is insane. One can twist every word every which (no pun intended) way. Not just words have infinite possible associations, gestures too, even noises. A lot stronger ones than words even. Audio triggers fight or flight, written words are passive.
Another little secret: I get incredibly anxious when I hear the sound of keys opening doors. You can guess why. Heart-rate doubling until I can tell myself 'it's just next door'. Many years later I still can't shake it.
Do I demand that people turn their locks in slow-motion so I don't hear it? No, of course I don't. I'm not an abusive witch-hunter, after all.

Not even a thanks for providing detailed information. That's what you get for helping.
