### ISSUE TITLE
Constant-Time fuzzing results

### ISSUE THREAD

**Issue by phayes** [BLAKE3-team/BLAKE3#27]
I built a bunch of constant-time fuzzing targets for blake3 using [sidefuzz](https://github.com/phayes/sidefuzz)

The fuzzing targets can be found here: http://github.com/phayes/sidefuzz-targets

Results are as follows:
 - hash (input): constant time ✔️ 
 - keyed_hash (input): constant time ✔️
 - keyed_hash (key): constant time ✔️
 - keyed_hash (key): constant time ✔️
 - reference_impl_hash (input): constant time ✔️
 - keyed_hash (key_material): constant time ✔️
 - keyed_hash (context): fuzzing-failed 

So everything looks good except that I couldn't properly fuzz `keyed_hash` in relation to the context since it takes a string, and sidefuzz produces `&[u8]`s as it's fuzzing inputs. 

So to fuzz `keyed_hash` in relation to `context` we would either need to resolve #13 or I would need to improve sidefuzz to have a function that provides a string.

**Comment by oconnor663** [comment]
Glad to hear we didn't do anything catastrophically wrong :-D

I wonder if you could work around the string issue by just converting the fuzz input to a hexadecimal string, and using that as the context? Or maybe masking off the high bit of each byte to make it valid ASCII, and then converting with `std::str::from_utf8`? I suppose the fully correct thing to do would be to generate a series of randomly chosen valid Unicode code points, but maybe that's more complicated than it really needs to be.

**Comment by phayes** [comment]
@oconnor663 -  I'll work on adding string support to SideFuzz - that should solve the issue. 

Being able to fuzz string inputs is something sidefuzz should have anyways, so this is fine. I'll update this ticket when it's done and I have results.

**Comment by oconnor663** [comment]
Going to close this one for now, but please do comment again if you get new results.
