### ISSUE TITLE
Blake3 in React - Cannot Read Properties of Undefined

### ISSUE THREAD

**Issue by renchris** [BLAKE3-team/BLAKE3#270]
I am importing the blake3 package to use in my front-end React application so I can create a front-end demo to use.

I have used the code in the example
`  import blake3 from 'blake3'
  const hashed = blake3.hash('foo') // => Buffer`
However I get an error of 
`Server Error
TypeError: Cannot read properties of undefined (reading 'hash')`

**Comment by oconnor663** [comment]
It looks like you're using a JS implementation of BLAKE3, presumably [this one](https://github.com/connor4312/blake3)? You might want to take a look at [the quickstart examples](https://github.com/connor4312/blake3#quickstart) if you're having trouble getting started? Hopefully that clears everything up, but if you suspect there's a real bug, you'll want to file it there.
