### ISSUE TITLE
[Question] Can BLAKE3 have similar security/collision resistance if used like Blake2x?

### ISSUE THREAD

**Issue by phantomcraft** [BLAKE3-team/BLAKE3#274]
I know that BLAKE3 can act as a XOF (extendable output function), but my use case is very sensitive.

BLAKE2x uses the following scheme:

B2(0, 64, H0)‖B2(1, 64, H0)‖B2(2, 64, H0)‖B2(3, 64, H0)‖B2(4, 64, H0)‖...

0, 1, 2 are the block counters, 64 is the hash digest length and H0 the seed to be hashed.

If I replace underlying BLAKE2 with BLAKE3, will I have the same collision resistance and security?

**Comment by phantomcraft** [comment]
I committed a mistake, 0, 1, 2 are not "block counters", are node offsets which is a BLAKE2 parameter, not sure if it would be possible to implement with BLAKE3.

Closing this.

**Comment by oconnor663** [comment]
For what it's worth, the space in the compression function where the BLAKE2 parameter block used to go is the same space where BLAKE3 puts the key. So you could come up with something almost exactly the same as BLAKE2X by putting a counter in the key bytes. But like you said, the built-in XOF means there's no need to do this.
