### ISSUE TITLE
help: Is there any way to use this awesome lib in NodeJs? 

### ISSUE THREAD

**Issue by mk48** [BLAKE3-team/BLAKE3#28]
I am NodeJs developer and would like to use this for my NodeJs project. Is there any way to use it?

**Comment by oconnor663** [comment]
@connor4321 has written some WASM bindings: https://github.com/connor4312/blake3 (third-party software, use at your own risk)

**Comment by mk48** [comment]
Thanks @oconnor663 for the quick response.
