### ISSUE TITLE
PostgreSQL extension

### ISSUE THREAD

**Issue by tobwen** [BLAKE3-team/BLAKE3#29]
I'm no C coder, but perhaps we can achieve this together?

https://www.percona.com/blog/2019/04/05/writing-postgresql-extensions-is-fun-c-language/

**Comment by oconnor663** [comment]
Paging @thinkxp :)

**Comment by oconnor663** [comment]
I'm going to close this issue for now, but feel free to reopen if you start work.

**Comment by beborngod** [comment]
did anyone manage to impl ps extension after 6 years?
