### ISSUE TITLE
Provide optional serde support for blake3::Hash

### ISSUE THREAD

**Issue by rklaehn** [BLAKE3-team/BLAKE3#290]
It would be convenient for blake3::Hash to have optional serde support.

I checked if other hashing libs do this. E.g. the sha2 lib directly produces `GenericArray`, which does support serde.

So - it is not the end of the world if you don't want to do it, but it would be nice and very straightforward to implement.

**Comment by oconnor663** [comment]
This also came up in https://github.com/BLAKE3-team/BLAKE3/pull/147. I'm kind of 50/50 on the idea. A couple of disorganized thoughts:

- I've been thinking of factoring out the `Hash` type into its own separate library, which could be shared with other crates. It already supports constant-time comparison and hex encoding/decoding, which is code that I find myself copy-pasting to other hash implementations I maintain. Maybe with a factored-out implementation, it would make more sense to add features like this.
- Is there a way to control whether serde serializes things as a list of ints vs as a hex string? I imagine some users would want one, and other users would want the other.

**Comment by rklaehn** [comment]
So this external hash crate would be not just for blake3 hashes but for generic hashes, and provide things like constant-time ops that are relevant for hashes? That would be nice. But then would you have to wrap it into a newtype to prevent mixing different kinds of hashes?

Regarding the serde thing. Not sure what is the best way to do it. But there is a mechanism in serde to detect whether a format intends to be human readable. Maybe use that to detect whether to use blob or hex string?

https://docs.rs/serde/latest/serde/trait.Deserializer.html#method.is_human_readable

**Comment by qti3e** [comment]
This code which I've written before exactly does this, and I don't think it needs any modification and can be copy-pasted into the codebase and activated with a `serde` feature flag. This uses hex encoding for human-readable formats (such as JSON and toml) and a fixed-size binary slice in binary formats (such as barcode, cbor, etc.)

See the test cases at the end of the same file.

https://github.com/qti3e/ross/blob/6cfb3502de90bca4a1444dd43a1d746c9a49060a/ross_core/src/utils/hash.rs#L84-L179

Let me know if you want this as a feature, and I'll happily open a pull request.

**Comment by oconnor663** [comment]
I've cobbled together what I think a generic, Serde-supporting `Hash` type might look like: https://github.com/oconnor663/cryptographic_hash. Unfortunately, it looks like the implementation will be pretty awkward without some more const generics features in stable. Curious to get other people's thoughts.

**Comment by rminderhoud** [comment]
I have opened a new pull request to add the optional serde feature. I think this is a nice quality of life for consumers of the library who want to use the `blake3::Hash` struct directly in their own structs, e.g.

```
#[derive(Serialize, Deserialize)]
struct MyStruct {
  some_hash: blake3::Hash; // Doesn't work without custom serializer/deserializer implementation
}
```

> Is there a way to control whether serde serializes things as a list of ints vs as a hex string? I imagine some users would want one, and other users would want the other.

My expectation as a serde user is that it would serialize as bytes, for custom serialization the expectation is to use a bespoke implementation, e.g. `serde_json` or similar and/or writing a custom implementation of serialize/deserialize trait. I'd be rather surprised if the default was to serialize the hex string.

> I've been thinking of factoring out the Hash type into its own separate library, which could be shared with other crates. It already supports constant-time comparison and hex encoding/decoding, which is code that I find myself copy-pasting to other hash implementations I maintain. Maybe with a factored-out implementation, it would make more sense to add features like this.

This is nice but in the meantime I think we can benefit from the QoL of the optional feature until such a project is complete?

From the old PR:

> What are the tradeoffs with implementing Serde traits on Hash, vs having the caller convert a hash to [u8; 32] with .into() and serialize those bytes directly? I tend to think of Hash as a convenience wrapper to make .to_hex() available, and as an opportunity for the documentation to ask the user to think about constant-time comparisons. But callers who plan on reading and writing the bytes of a hash will probably have an easier time if they convert the hash to bytes immediately?

I don't see a downside to have an optional derive for those that want it. For those who have different plans for the hash (e.g. serialize as hex string) or some other behavior I think they would write their own serialize/deserialize/visitor etc.
