### ISSUE TITLE
doesnt work , unknown b3sum file , on arm 8 phone in proot debian via termux

### ISSUE THREAD

**Issue by fxmbsw7** [BLAKE3-team/BLAKE3#292]
hello ,
i am rust noob , otherwhere pro ..
i did rustup install nightly conplete
then did cargo install b3sum ( i think from readme i dunno , site says add
but i didnt know and did install , i just after fixing this will try add
.. the cargo installer did lots output and finally exited with b3sum installed
but i type b3sum it says unknown command
.. i found out its some special .. i dunno
the shell completes to .cargo/bin/b3sum but rest fails

root@localhost:~# file .cargo/bin/b3sum
.cargo/bin/b3sum: cannot open `.cargo/bin/b3sum' (No such file or directory)
root@localhost:~# ls -l .cargo/bin
ls: cannot access '.cargo/bin/b3sum': No such file or directory
total 198588
l??????????  ? ?    ?           ?            ? b3sum
-rwxr-xr-x. 13 root root 15624696 Feb 11 15:12 cargo
-rwxr-xr-x. 13 root root 15624696 Feb 11 15:12 cargo-clippy
-rwxr-xr-x. 13 root root 15624696 Feb 11 15:12 cargo-fmt
-rwxr-xr-x. 13 root root 15624696 Feb 11 15:12 cargo-miri
-rwxr-xr-x. 13 root root 15624696 Feb 11 15:12 clippy-driver
-rwxr-xr-x. 13 root root 15624696 Feb 11 15:12 rls
-rwxr-xr-x. 13 root root 15624696 Feb 11 15:12 rust-gdb
-rwxr-xr-x. 13 root root 15624696 Feb 11 15:12 rust-gdbgui
-rwxr-xr-x. 13 root root 15624696 Feb 11 15:12 rust-lldb
-rwxr-xr-x. 13 root root 15624696 Feb 11 15:12 rustc
-rwxr-xr-x. 13 root root 15624696 Feb 11 15:12 rustdoc
-rwxr-xr-x. 13 root root 15624696 Feb 11 15:12 rustfmt
-rwxr-xr-x. 13 root root 15624696 Feb 11 15:12 rustup

system is debian unstable / experimental on arm8 via proot ( noroot ) via termux terninal / system

greets

**Comment by oconnor663** [comment]
Hmm, getting a bunch of question marks from `ls` is very suspicious. I'm guessing the problem isn't with `b3sum` in particular, but with something about how your toolchain is installed. Could you try installing another Rust program (for example, `cargo install ripgrep`) and see if you get a similar result?

**Comment by fxmbsw7** [comment]
i tried and its same
last lines ..

Compiling grep v0.2.11
    Finished release [optimized + debuginfo] target(s) in 2m 26s
  Installing /root/.cargo/bin/rg
   Installed package `ripgrep v13.0.0` (executable `rg`)
root@localhost:~# rg
bash: rg: command not found
root@localhost:~#

i looked from outside the proot chroot
it fails also ..
im not sure , but maybe its simple cause it links ( maybe invalidly ) to some /tmp path ..

~ $ ls -l debian-fs/root/.cargo/bin
total 0
lrwxrwxrwx 1 u0_a268 u0_a268 111 Feb 11 16:23 b3sum -> /data/data/com.termux/files/home/debian-fs/tmp/cargo-installpF17KM/release/deps/.l2s.b3sum-8412ea923008c46a0001
lrwxrwxrwx 1 u0_a268 u0_a268  74 Feb 11 16:12 cargo -> /data/data/com.termux/files/home/debian-fs/root/.cargo/bin/.l2s.rustup0001
lrwxrwxrwx 1 u0_a268 u0_a268  74 Feb 11 16:12 cargo-clippy -> /data/data/com.termux/files/home/debian-fs/root/.cargo/bin/.l2s.rustup0001
lrwxrwxrwx 1 u0_a268 u0_a268  74 Feb 11 16:12 cargo-fmt -> /data/data/com.termux/files/home/debian-fs/root/.cargo/bin/.l2s.rustup0001
lrwxrwxrwx 1 u0_a268 u0_a268  74 Feb 11 16:12 cargo-miri -> /data/data/com.termux/files/home/debian-fs/root/.cargo/bin/.l2s.rustup0001
lrwxrwxrwx 1 u0_a268 u0_a268  74 Feb 11 16:12 clippy-driver -> /data/data/com.termux/files/home/debian-fs/root/.cargo/bin/.l2s.rustup0001
lrwxrwxrwx 1 u0_a268 u0_a268 108 Feb 12 08:22 rg -> /data/data/com.termux/files/home/debian-fs/tmp/cargo-installaMRU0H/release/deps/.l2s.rg-945c8d674ebab8cf0001
lrwxrwxrwx 1 u0_a268 u0_a268  74 Feb 11 16:12 rls -> /data/data/com.termux/files/home/debian-fs/root/.cargo/bin/.l2s.rustup0001
lrwxrwxrwx 1 u0_a268 u0_a268  74 Feb 11 16:12 rust-gdb -> /data/data/com.termux/files/home/debian-fs/root/.cargo/bin/.l2s.rustup0001
lrwxrwxrwx 1 u0_a268 u0_a268  74 Feb 11 16:12 rust-gdbgui -> /data/data/com.termux/files/home/debian-fs/root/.cargo/bin/.l2s.rustup0001
lrwxrwxrwx 1 u0_a268 u0_a268  74 Feb 11 16:12 rust-lldb -> /data/data/com.termux/files/home/debian-fs/root/.cargo/bin/.l2s.rustup0001
lrwxrwxrwx 1 u0_a268 u0_a268  74 Feb 11 16:12 rustc -> /data/data/com.termux/files/home/debian-fs/root/.cargo/bin/.l2s.rustup0001
lrwxrwxrwx 1 u0_a268 u0_a268  74 Feb 11 16:12 rustdoc -> /data/data/com.termux/files/home/debian-fs/root/.cargo/bin/.l2s.rustup0001
lrwxrwxrwx 1 u0_a268 u0_a268  74 Feb 11 16:12 rustfmt -> /data/data/com.termux/files/home/debian-fs/root/.cargo/bin/.l2s.rustup0001
lrwxrwxrwx 1 u0_a268 u0_a268  74 Feb 11 16:12 rustup -> /data/data/com.termux/files/home/debian-fs/root/.cargo/bin/.l2s.rustup0001
~ $ ls -l debian-fs/root/.cargo/bin/rg
lrwxrwxrwx 1 u0_a268 u0_a268 108 Feb 12 08:22 debian-fs/root/.cargo/bin/rg -> /data/data/com.termux/files/home/debian-fs/tmp/cargo-installaMRU0H/release/deps/.l2s.rg-945c8d674ebab8cf0001
~ $ debian-fs/root/.cargo/bin/rg
bash: debian-fs/root/.cargo/bin/rg: No such file or directory
~ $ ls -l /data/data/com.termux/files/home/debian-fs/tmp/cargo-installaMRU0H/release/deps/.l2s.rg-945c8d674ebab8cf0001
ls: cannot access '/data/data/com.termux/files/home/debian-fs/tmp/cargo-installaMRU0H/release/deps/.l2s.rg-945c8d674ebab8cf0001': No such file or directory
~ $ ls -l /data/data/com.termux/files/home/debian-fs/tmp/cargo-installaMRU0H/release/deps/
ls: cannot access '/data/data/com.termux/files/home/debian-fs/tmp/cargo-installaMRU0H/release/deps/': No such file or directory

.. btw thank you for your reply
.. greets

**Comment by fxmbsw7** [comment]
btw about rust , to update / nightly , do i have to run the rustup install line , or is there some update cmd

**Comment by fxmbsw7** [comment]
maybe link me to the rust mailing list ..

**Comment by fxmbsw7** [comment]
as i have not much rust exp , a mate suggested me
cargo build --release
which worked in the b3sum/ dir inside the git
and the outcome seems to work too

root@localhost:~/blake3.git/b3sum/target# cd release/                      root@localhost:~/blake3.git/b3sum/target/release# ls                       b3sum  b3sum.d  build  deps  examples  incremental                         root@localhost:~/blake3.git/b3sum/target/release# file b3sum               b3sum: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=9c9ae329080a7a223026fd7276b836e0d7cb0195, for GNU/Linux 3.7.0, with debug_info, not stripped

**Comment by oconnor663** [comment]
`cargo install b3sum` and `cd BLAKE3/b3sum && cargo build --release` should produce exactly the same binary, so I'm still not clear on exactly what could've been going wrong before. I will say that "debian unstable / experimental on arm8 via proot" sounds like a frightening combination :)

If you run into any more toolchain issues like this, I'd suggest asking folks on the Rust community Discord server. You can find a link here: https://www.rust-lang.org/community

**Comment by fxmbsw7** [comment]
ill try there
.. should the install cmd cp the b3sum bin into bin/ ? cause mine is only a sym link , to some in /tmp/

**Comment by oconnor663** [comment]
You can `cp` these executables wherever you like, yes. Normally I'd recommend adding `~/.cargo/bin` to your `$PATH`, so that anything you `cargo install` is automatically runable in the terminal, but maybe that doesn't make sense until you figure out the ???????? problem that `cargo install` was giving you...
