### ISSUE TITLE
[Question] How can Blake3 tested by SMhasher suite be fast as hell?

### ISSUE THREAD

**Issue by alpominth** [BLAKE3-team/BLAKE3#295]
When Blake3 is benchmarked by SMhasher suite, it yields 1288.84 MiB/S of hash output in a AMD Ryzen 5 3350G 3.6GHz (a modern processor).

Ok, but the author said that the key hashed has 262144-bytes of size and is processed entirely and sequentially, over and over.

1288.84MiB equals ~1351446691-bytes that means ~42232709 outputs of Blake3 having then 32-bytes each one.

If we multiple the number of outputs by each key processed we have this: 42232709 * 262144 = 11071051268096-bytes read as input (11.07-terabytes).

My question is:

How can it be possible that the input of Blake3 tested peaks at 11.07-terabytes per second?

I could think: Is the L1/L2 CPU cache, but L1 cache of modern processors has a speed of 2.3-terabytes per second, L2 is more slower than that.

Can someone here explain that?

A user of a forum said that the 262144-bytes builds up a fast internal hash table, and the subsequent invocations of compression function perform the lookups on the hash table. That's why would be so fast. Is that true?

**Comment by sneves** [comment]
From [what I can see](https://github.com/rurban/smhasher/blob/82e7844c75d9c288f4833b1c1309ee4f3d629c3f/SpeedTest.cpp#L271), the SMHasher speed test measures the speed at which the hash can process input, not produce output data.
