### ISSUE TITLE
Report RUSTSEC vulnerability for issue #206

### ISSUE THREAD

**Issue by asomers** [BLAKE3-team/BLAKE3#297]
The release notes describe issue #206 as a security vulnerability: https://github.com/BLAKE3-team/BLAKE3/releases/tag/1.2.0 .  If true, could you please report a RUSTSEC vulnerability, to help notify users?
https://rustsec.org/contributing.html

**Comment by oconnor663** [comment]
https://github.com/rustsec/advisory-db/issues/1666
