### ISSUE TITLE
C-cpuid (very small) bug?

### ISSUE THREAD

**Issue by fcorbelli** [BLAKE3-team/BLAKE3#300]
Hello, here

https://github.com/BLAKE3-team/BLAKE3/blob/master/c/blake3_dispatch.c

@lines 104-105
```
    if (*ecx & (1UL << 0))
      features |= SSSE3;
```
But the SSSE3 should be bit 9
https://www.felixcloutier.com/x86/cpuid

SSE3 is bit 0, just like in your code
(Intel, I really love you!)

**Comment by sneves** [comment]
You're right; I can't tell whether this was a typo or a SSE3/SSSE3 mixup.
