### ISSUE TITLE
b3sum incredibly slow

### ISSUE THREAD

**Issue by tERyceNzAchE** [BLAKE3-team/BLAKE3#32]
b3sum runs incredibly slow.

PC:
Windows 10 Pro
i7-6700
32GB RAM

b3sum built using: `cargo install b3sum` (v0.1.2)

Test File: 2.88GB

Results:
```
md5sum: 10 seconds
b2sum: 5 seconds
b3sum: 4 Minutes 37 Seconds
```

**Comment by oconnor663** [comment]
Out of curiosity, what happens if you hash via stdin like this: `b3sum < big_file` (does that work on Windows)

**Comment by tERyceNzAchE** [comment]
That took it from minutes to seconds!

**Comment by oconnor663** [comment]
Cool. "Thrashing the disk" is my current theory for your slow numbers. The next thing I'd be curious to try is a file small enough to fit in memory. That should work better with all the threads, because you won't actually be hitting the disk do much. Also, do you happen to have a spinning drive?

**Comment by tERyceNzAchE** [comment]
Yes, this is from a spinning drive.

**Comment by oconnor663** [comment]
"Don't bother with multi-threading when you're on a spinning drive and the file is too small to fit in cache" would be a decent performance heuristic, but I don't know of any simple or reliable way to detect either of those two conditions...

**Comment by oconnor663** [comment]
You know, I wonder if the performance problem here is *audible* :)

**Comment by tERyceNzAchE** [comment]
> I wonder if the performance problem here is audible :)

It does seem to be.

**Comment by tERyceNzAchE** [comment]
> "Don't bother with multi-threading when you're on a spinning drive and the file is too small to fit in cache" would be a decent performance heuristic, but I don't know of any simple or reliable way to detect either of those two conditions...

This isn't a small file.  Perhaps a command line flag to disable multi-threading?

**Comment by oconnor663** [comment]
Oops, meant to say "too large" above. Some flag like that might be useful for benchmarking and testing (situations like this), and we could totally add it. That said, I don't expect that most users facing this sort of issue will be able to discover that the `--single-threaded` flag (or whatever we call it) fixes things.

**Comment by xzfc** [comment]
This isn't documented in b3sum itself, but you can disable multi-threading by setting `RAYON_NUM_THREADS=1` environment variable.

**Comment by tERyceNzAchE** [comment]
> This isn't documented in b3sum itself, but you can disable multi-threading by setting RAYON_NUM_THREADS=1 environment variable.

This didn't make a significant difference (like `b3sum < big_file` did).

**Comment by oconnor663** [comment]
Interesting. I wonder if memory mapping itself is leading to thrashing, even if the access pattern of the mapping is serial? I don't know enough about the inner working of memory mapping to say, and especially not on Windows.

**Comment by oconnor663** [comment]
I'm going to close this issue for now, but we can re-open if it starts to look like there's something `b3sum` itself should be doing differently in the default case.
