### ISSUE TITLE
Question: How to compile and run benches/bench.rs?

### ISSUE THREAD

**Issue by przemyslaw0** [BLAKE3-team/BLAKE3#321]
How can I compile and run the file benches/bench.rs?

I tried to compile with **cargo build --release** but I don't see any executable in BLAKE3 folders being generated.

**Comment by oconnor663** [comment]
I usually run benchmarks with `cargo +nightly bench`. The `+nightly` part assumes you've installed Rust and Cargo using `rustup` and that you've also installed the nightly toolchain (`rustup install nightly`). If you don't want to do that, it's also possible to run benchmarks on the stable toolchain like this: `RUSTC_BOOTSTRAP=1 cargo bench`

**Comment by oconnor663** [comment]
"1 block" is 64 bytes. You can follow that at these points in the code:
- https://github.com/BLAKE3-team/BLAKE3/blob/760ed6a8bfef14cfff7432dd21235627d6e42c47/benches/bench.rs#L228
- https://github.com/BLAKE3-team/BLAKE3/blob/760ed6a8bfef14cfff7432dd21235627d6e42c47/src/guts.rs#L9

"1 kib" means 1024 bytes. You can follow that here:
- https://github.com/BLAKE3-team/BLAKE3/blob/760ed6a8bfef14cfff7432dd21235627d6e42c47/benches/bench.rs#L233C25-L233C25
- https://github.com/BLAKE3-team/BLAKE3/blob/760ed6a8bfef14cfff7432dd21235627d6e42c47/benches/bench.rs#L13
