### ISSUE TITLE
Fix build for big endian AArch64 hosts

### ISSUE THREAD

**Issue by kovdan01** [BLAKE3-team/BLAKE3#336]
Implementation only supports using arm neon for little endian hosts, while the corresponding `BLAKE3_USE_NEON` macro is set for all AArch64 hosts unconditionally. This causes a build error: see https://github.com/BLAKE3-team/BLAKE3/blob/master/c/blake3_neon.c#L6. Submitted a PR fixing this behavior: https://github.com/BLAKE3-team/BLAKE3/pull/335

**Comment by ThomasWaldmann** [comment]
You made me curious: what kind of hosts and OSes are there for big-endian aarch64?

**Comment by kovdan01** [comment]
I can't say for sure :) I was checking this "just in case" as a part of another project to ensure that code works properly for both endiannesses, and I have chosen aarch64 BE since a prebuilt cross-toolchain was available for it.

**Comment by kovdan01** [comment]
Close as fixed in https://github.com/BLAKE3-team/BLAKE3/pull/280
