### ISSUE TITLE
One comma too many

### ISSUE THREAD

**Issue by fcorbelli** [BLAKE3-team/BLAKE3#348]
In blake3_impl.h

```
// internal flags
enum blake3_flags {
  CHUNK_START         = 1 << 0,
  CHUNK_END           = 1 << 1,
  PARENT              = 1 << 2,
  ROOT                = 1 << 3,
  KEYED_HASH          = 1 << 4,
  DERIVE_KEY_CONTEXT  = 1 << 5,
  DERIVE_KEY_MATERIAL = 1 << 6,
};
```

The very last one throw a warning   
Not a very big issue, of course

**Comment by sicherha** [comment]
The trailing comma is there on purpose: it has the advantage that a subsequent addition of further enum elements could be done with a minimal diff, without having to append a comma to an existing line.

The 'trailing-comma' feature was introduced in the ISO C99 standard. Nowadays modern compilers default to C11 or later, so they should build this code without warning.

Which version of which compiler are you using? What is the exact warning message?

**Comment by fcorbelli** [comment]
It is on ancient slackware compiler, I do not get the exact message, not really important
One of my favorite ways, to look for warnings, is just to use older compilers, even from 10 or 15 years ago
And yes, I leave the , for the same reason, too 😄

**Comment by fcorbelli** [comment]
Your help is invaluable, especially if you explain what you like, and what you don't, about zpaqfranz
What aspects could be better

**Comment by sicherha** [comment]
The use of C99 could be made explicit by adding to `CMakeLists.txt`:
```cmake
set(CMAKE_C_STANDARD 99)
set(CMAKE_C_STANDARD_REQUIRED ON)
```

**Comment by oconnor663** [comment]
> The use of C99 could be made explicit by adding to `CMakeLists.txt`:
> 
> ```cmake
> set(CMAKE_C_STANDARD 99)
> set(CMAKE_C_STANDARD_REQUIRED ON)
> ```

@BurningEnlightenment do you think we should do something along these lines?
