### ISSUE TITLE
(Feature request) Create hashes for remote files with b3sum

### ISSUE THREAD

**Issue by hardBSDk** [BLAKE3-team/BLAKE3#366]
The command `b3sum https://github.com/BLAKE3-team/BLAKE3/archive/refs/tags/1.5.0.tar.gz` would download the tarball to the temporary folder and create a hash for it.

It's useful when the user don't want to download the file.

**Comment by oconnor663** [comment]
With no arguments, `b3sum` will hash standard input, so you can do something like this:

```
curl -L https://github.com/BLAKE3-team/BLAKE3/archive/refs/tags/1.5.0.tar.gz | b3sum
```

**Comment by BurningEnlightenment** [comment]
To clarify: This feature is not intended to be implemented directly in b3sum.
