### ISSUE TITLE
Add method `reset` for `Hasher` ?

### ISSUE THREAD

**Issue by LuoZijun** [BLAKE3-team/BLAKE3#41]
Will this be useful in scenarios where hash calculations are very frequent?

**Comment by oconnor663** [comment]
Resetting a `Hasher` should be pretty much the same thing as re-initializing it with `Hasher::new`. The only exception I can think of would be if the assignment decides to memcpy the entire CV stack, even though most of it is uninitialized garbage bytes. That might be unnecessarily expensive, but I've never measured it myself. We might also be able to fix that by making sure the constructors are marked `#[inline]`.
