### ISSUE TITLE
1.5.2 breaks serialization for formats like "bincode"

### ISSUE THREAD

**Issue by nullchinchilla** [BLAKE3-team/BLAKE3#414]
> Serializing a Hash produces a bytestring instead of an array in
formats that support bytestrings (like CBOR). Deserialization is
backwards-compatible with the array format.

This is *not* backwards compatible for formats like "bincode", where it's not possible to first try to deserialize as an array and then try deserialization as a bytestring. Previously serialized and saved `Hash`es will now fail on deserialization.

This has actually broken a large production system I run that currently must be pegged to 1.5.1 as a result. Please at least make this feature optional, or enable it only for human-readable serde formats like JSON.

**Comment by oconnor663** [comment]
I'll revert this change tonight, and then we can consider whether there's a better way to accomplish the same thing. Do you have time to put together a small program that reproduces the break you're seeing?

**Comment by oconnor663** [comment]
I've published v1.5.3 with the revert. Let me know if you can confirm that it fixes your system.

**Comment by nullchinchilla** [comment]
Yes it does fix it!

I think a better way of doing this is probably to check [whether the format is human readable](https://docs.rs/serde/latest/serde/trait.Serializer.html#method.is_human_readable), which might be a good proxy for whether it's self-describing.

But I think probably the best way is to release 2.0 instead.

**Comment by BurningEnlightenment** [comment]
> I think a better way of doing this is probably to check [whether the format is human readable](https://docs.rs/serde/latest/serde/trait.Serializer.html#method.is_human_readable), which might be a good proxy for whether it's self-describing.

CBOR, JSONB and MessagePack would be missed by that check, right?
