### ISSUE TITLE
meaningless benchmark

### ISSUE THREAD

**Issue by greenpdx** [BLAKE3-team/BLAKE3#433]
I just did a blake3 hash of over 16,000 movies file and databased them into a sqlite database.
size: 2270677986839
time: 54555.376517945s

2.3 TB
in about 15 hours
Mb / sec 41.6 

async fn file_hash(pth: &Path) -> Result<String, Box<dyn Error>> {
    let mut hasher = Hasher::new();

    hasher.update_mmap_rayon(pth)?;

    Ok(hasher.finalize().to_hex().to_ascii_lowercase())
}

**Comment by oconnor663** [comment]
I'm afraid in that use case you're almost certainly benchmarking your disk read speed and not how fast your CPU can hash the data.
