### ISSUE TITLE
Is there a reason for arrayvec being locked to version 0.7.4?

### ISSUE THREAD

**Issue by murl-digital** [BLAKE3-team/BLAKE3#434]
Since BLAKE3's a dependency for surrealdb, I'm trying to use it in a project with the image crate, which causes a dependency conflict. I'm assuming there's a reason that arrayvec's locked to 0.7.4 (probably for the memory layout changes in 0.7.5) but it's a blocker for me right now. Could it be updated?

**Comment by oconnor663** [comment]
I don't think we're locking the version of `arrayvec` we use. When I do a clean build of this repo, it pulls in version 0.7.6. Is it possible you just need to delete your `Cargo.lock` file or similar?

**Comment by murl-digital** [comment]
You're right, my bad. Turns out another dependency in my project is explicitly locking to 0.7.4, I'll close this out
