### ISSUE TITLE
[C/main.c] function memset used before return of malloc was done.

### ISSUE THREAD

**Issue by TheVice** [BLAKE3-team/BLAKE3#45]
Hello.

In **main.c** _memset_ was call on memory before this block was checked on NULL after it get from _malloc_ function. One of solution placed it after this check was done.

Next [pull request](https://github.com/BLAKE3-team/BLAKE3/pull/46) can be applied to do this.

Thank you.

P.S.
Also **out_len** can be check before _malloc_, but that is different story.

**Comment by oconnor663** [comment]
> Also out_len can be check before malloc, but that is different story.

`main.c` is only used for testing, so performance doesn't particularly matter here.

**Comment by TheVice** [comment]
By the way, creating of 'out' [can be moved](https://github.com/BLAKE3-team/BLAKE3/pull/49) outside of 'do' loop.

Also we can discuss about using preferred size of buffer base on 64 and in this case internal buffer 'wide_buf' [can be removed](https://github.com/BLAKE3-team/BLAKE3/pull/50). This request marked as WIP according to not pass checking at moment when this comment was written.
