### ISSUE TITLE
[MSVC] support of Microsoft C compiler is missed.

### ISSUE THREAD

**Issue by TheVice** [BLAKE3-team/BLAKE3#47]
Hello.

There is a series of issues at source files that prevent to compile project at Microsoft C compiler:
- including of POSIX header;
- applying of unary minus operator to the unsigned value;
- including of header that not applying to the all target platforms (ARM/x86/...).

One of vision how to resolve that all can be found in [this request](https://github.com/BLAKE3-team/BLAKE3/pull/48).

Thank you.

P.S.
Please note, here we talking about compile issue. Linking at MSVC environment have same issue like at gcc that already discussed [here](https://github.com/BLAKE3-team/BLAKE3/issues/16).

**Comment by oconnor663** [comment]
That PR has been merged, so I'm going to go ahead and close this issue. We can reopen this one or another one if more bugs crop up.
