### ISSUE TITLE
Cargo.toml license entry doesn't match LICENSE file

### ISSUE THREAD

**Issue by Lokathor** [BLAKE3-team/BLAKE3#5]
The license file says CC0 or Apache-2.0, but the Cargo.toml only lists Apache-2.0

You can use OR to make it an option, so `CC0 OR Apache-2.0`

**Comment by oconnor663** [comment]
When I first uploaded the crates, crates.io rejected CC0. Will it be more permissive with the OR?

**Comment by Lokathor** [comment]
Ah, my bad, crates.io enforces a whitelist of the SPDX codes and the SPDX code for CC0 is actually `CC0-1.0`, so try with that

**Comment by bbqsrc** [comment]
Made a pull request for this: https://github.com/BLAKE3-team/BLAKE3/pull/12

**Comment by oconnor663** [comment]
Merged, thanks. Should be fixed with the next release.
