### ISSUE TITLE
regenerate the graphs

### ISSUE THREAD

**Issue by oconnor663** [BLAKE3-team/BLAKE3#63]
There have been quite a few performance improvements since we originally published the paper and the big red bar chart. We should redo them.

**Comment by oconnor663** [comment]
Done.

**Comment by divinity76** [comment]
speaking of, can someone explain this?

``` 
root@x2ratma:~# time b2sum 1GB
9ba5dba8be8c8ab1474e7dbe5c7d2fb29c8d161beb5a5d4410b342445c60ab1dd895062c3561d3b128e96938a11a1c89a80169b3e3654dbf76b6eed50dc5e1c6  1GB

real    0m1.985s
user    0m1.821s
sys     0m0.164s
root@x2ratma:~# time b2sum 1GB
9ba5dba8be8c8ab1474e7dbe5c7d2fb29c8d161beb5a5d4410b342445c60ab1dd895062c3561d3b128e96938a11a1c89a80169b3e3654dbf76b6eed50dc5e1c6  1GB

real    0m1.984s
user    0m1.815s
sys     0m0.168s
root@x2ratma:~# time b2sum 1GB
9ba5dba8be8c8ab1474e7dbe5c7d2fb29c8d161beb5a5d4410b342445c60ab1dd895062c3561d3b128e96938a11a1c89a80169b3e3654dbf76b6eed50dc5e1c6  1GB

real    0m1.985s
user    0m1.860s
sys     0m0.124s
root@x2ratma:~# time b3sum 1GB
94b4ec39d8d42ebda685fbb5429e8ab0086e65245e750142c1eea36a26abc24d  1GB

real    0m0.095s
user    0m1.687s
sys     0m0.074s
root@x2ratma:~# time b3sum 1GB
94b4ec39d8d42ebda685fbb5429e8ab0086e65245e750142c1eea36a26abc24d  1GB

real    0m0.095s
user    0m1.681s
sys     0m0.107s
root@x2ratma:~# time b3sum 1GB
94b4ec39d8d42ebda685fbb5429e8ab0086e65245e750142c1eea36a26abc24d  1GB

real    0m0.096s
user    0m1.684s
sys     0m0.105s
root@x2ratma:~# cat /proc/cpuinfo  | grep name
model name      : Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz
```
(old 2010 32nm Westmere CPU)

that's not like 4-5 times faster, that's more like 20 times faster, guess b3sum is multithreading here? (while blake2b can't, and i'm not using blake2bp)

**Comment by oconnor663** [comment]
Correct. By default, `b3sum` is going to use multithreading (memory mapping too), and 1 GB is more than enough input to see the full benefits of that. You've got 6 physical cores, so you should expect nearly a 6x improvement in throughput on that basis alone. You can see that multithreading is happening because the reported "user" time is larger than the "real" time.

The other big factor is that BLAKE3 benefits substantially from the SSE4.1 SIMD instructions that your CPU supports. On my machine, the SSE4.1 implementation has 2.3x the per-thread throughput of the portable BLAKE2b implementation that I believe `b2sum` is using. (The AVX2 implementation of BLAKE3 is even faster, and the AVX-512 implementation is faster still.) Samuel mentioned that he wrote the SSE4.1 assembly with an eye towards older chips, and it's possible this part of the difference is larger on your machine.

So that's a factor of 14 or so that we can definitely account for. I'm not exactly sure what beyond that gets you to 20. It could be that the SSE4.1 advantage is larger for you than for me, like we just said. Or it could be that hyperthreading is helping. There's definitely some advantage to memory mapping, though not quite enough to make up this entire difference I think.

**Comment by divinity76** [comment]
sorry, i forgot that this is a dual-cpu system, it has 2x X5670 for a total of 12 physical cores, guess that explains the 20x then

also i just learned how to restrict cpu access on linux, and with just 1 cpu core access:

```
root@x2ratma:~# nproc
24
root@x2ratma:~# taskset -c 0 bash
root@x2ratma:~# nproc
1
root@x2ratma:~# time b2sum 1GB
9ba5dba8be8c8ab1474e7dbe5c7d2fb29c8d161beb5a5d4410b342445c60ab1dd895062c3561d3b128e96938a11a1c89a80169b3e3654dbf76b6eed50dc5e1c6  1GB

real    0m2.039s
user    0m1.866s
sys     0m0.172s
root@x2ratma:~# time b2sum 1GB
9ba5dba8be8c8ab1474e7dbe5c7d2fb29c8d161beb5a5d4410b342445c60ab1dd895062c3561d3b128e96938a11a1c89a80169b3e3654dbf76b6eed50dc5e1c6  1GB

real    0m2.040s
user    0m1.847s
sys     0m0.192s
root@x2ratma:~# time b3sum 1GB
94b4ec39d8d42ebda685fbb5429e8ab0086e65245e750142c1eea36a26abc24d  1GB

real    0m0.808s
user    0m0.776s
sys     0m0.032s
root@x2ratma:~# time b3sum 1GB
94b4ec39d8d42ebda685fbb5429e8ab0086e65245e750142c1eea36a26abc24d  1GB

real    0m0.810s
user    0m0.781s
sys     0m0.028s
```
seems to be 2.5x speedup with 1 core access :) (don't know if there is a way to tell b3sum to only use X amount of threads, but didn't find it with "b3sum --help" at least)

thanks for explaining

**Comment by oconnor663** [comment]
> this is a dual-cpu system

Oh huh, in that case the question is why we're _underperforming_.

> tell b3sum to only use X amount of threads

Currently `b3sum` uses the Rayon defaults, which means you can control the number of threads by setting `RAYON_NUM_THREADS=X` in the environment. If you want single-threading specifically, you can also use `--no-mmap` or hash input from stdin, either of which will disable threading.

In the future some of these things might change. I do plan on adding an explicit `--num-threads` flag eventually, or something along those lines.

**Comment by sneves** [comment]
Probably running into a memory bandwidth plateau with that many cores all fighting for memory bandwidth.
