### ISSUE TITLE
Cargo Clippy makes some good reccomendations

### ISSUE THREAD

**Issue by SteveBattista** [BLAKE3-team/BLAKE3#7]
If you run cargo clippy it seems to make some good recommendations. Things like:
1.You multiply 0*4 in many lines. The answer would be 0. It might be faster to replace these.
2. You multiply items by 1, you don't need the 1. 
3. You do some masking with a 0 (answer is only 0)
4. Some passing of small items might be faster if one does not use a reference.

**Comment by oconnor663** [comment]
Yes, I've looked at the clippy warnings. Most of them refer to code blocks like this:

```rust
loadu(inputs[0].add(block_offset + 0 * 4 * DEGREE)),
loadu(inputs[1].add(block_offset + 0 * 4 * DEGREE)),
loadu(inputs[2].add(block_offset + 0 * 4 * DEGREE)),
loadu(inputs[3].add(block_offset + 0 * 4 * DEGREE)),
loadu(inputs[0].add(block_offset + 1 * 4 * DEGREE)),
loadu(inputs[1].add(block_offset + 1 * 4 * DEGREE)),
loadu(inputs[2].add(block_offset + 1 * 4 * DEGREE)),
loadu(inputs[3].add(block_offset + 1 * 4 * DEGREE)),
loadu(inputs[0].add(block_offset + 2 * 4 * DEGREE)),
loadu(inputs[1].add(block_offset + 2 * 4 * DEGREE)),
loadu(inputs[2].add(block_offset + 2 * 4 * DEGREE)),
loadu(inputs[3].add(block_offset + 2 * 4 * DEGREE)),
loadu(inputs[0].add(block_offset + 3 * 4 * DEGREE)),
loadu(inputs[1].add(block_offset + 3 * 4 * DEGREE)),
loadu(inputs[2].add(block_offset + 3 * 4 * DEGREE)),
loadu(inputs[3].add(block_offset + 3 * 4 * DEGREE)),
```

Inlining these sorts of things, rather than hoping that the compiler will unroll a loop, is often important for performance. Once you write it out inline, the version that keeps the `0 * ...` and `1 * ...` is a lot easier to read, because it all lines up, and you can see the pattern more clearly.

**Comment by Rudxain** [comment]
I have a question about this. I've seen that `src/portable` makes heavy use of manual/explicit loop unrolling, even for small loops that just use 4/6/8 iterations. Is there still a benefit to doing this nowadays? If so, I recommend suing [this crate](https://crates.io/crates/unroll)
