### ISSUE TITLE
How to modify number of rounds we hash?

### ISSUE THREAD

**Issue by FractalMatt** [BLAKE3-team/BLAKE3#70]
I know that Blake3 hashes for 7 rounds, and I know that is believed to be secure enough, but it sounds like just barely so. I would like to be extra careful as I'm working on an application that needs paranoid levels of security.

Would be really nice if there were a simple way to just hash for a variable number of rounds, and I could simply add a few more, is that possible? If not, you might want to consider adding it. Fights off everyone who says Blake3 isn't as secure as Blake2 and seems easy enough to add.

The other option is to simply double or triple hash.. is there any reason that is not as secure as 14 or 21 rounds?

**Comment by oconnor663** [comment]
> I'm working on an application that needs paranoid levels of security.

Based on that description, you should not use a hash function that's two months old. I'd suggest following the "boring" recommendations here: https://latacora.micro.blog/2018/04/03/cryptographic-right-answers.html

> it sounds like just barely so.

It's important -- but also very difficult -- to be concrete with these things. Terms like "barely secure" are vague. On the one hand it sounds like something we don't want, like taking too many risks. On the other hand it sounds like something we do want, like achieving our security goal without wasting CPU cycles or battery power. The way to navigate this tradeoff is to make reference to known attacks and to choose an explicit risk model for future attacks. See https://eprint.iacr.org/2019/1492.pdf and Section 4.4 of [the BLAKE3 paper](https://github.com/BLAKE3-team/BLAKE3-specs/blob/master/blake3.pdf) for our take on this.

> Would be really nice if there were a simple way to just hash for a variable number of rounds, and I could simply add a few more, is that possible?

No, the downsides of such a feature dramatically outweigh the upsides.

For starters, any parameter of this kind adds costs in terms of implementation complexity and performance. For example, if the round number is variable, a hardware or assembly implementation can't fully unroll the round loop. Obscure options also turn into compatibility problems, when one implementation supports changing the parameter and another only supports the default value.

At the same time, the practical value of such a feature is low. We've picked a round number that we believe will never be attacked, which necessarily means we believe the value of increasing it is close to zero. Reducing the number of rounds is more likely to provide actual value -- for example, to an application that doesn't need collision resistance -- but of course in the real world it would be an unacceptable foot-gun, and tons of applications would accidentally choose a value that's too small. In practice, we'd need to select a minimum number of rounds that we believed was secure for everyone. If such a minimum exists, what's the benefit of increasing the number of rounds further?

Furthermore, expert users who believe they can competently evaluate the security of a round number, can fork the code. Making the round number variable isn't about making that possible, but rather about making it *convenient*. (Or about blessing it with the BLAKE/2/3 label.) But we believe exactly the opposite: the vast, *vast* majority of applications should use the same secure defaults, and dangerous choices should be very inconvenient.

> The other option is to simply double or triple hash.. is there any reason that is not as secure as 14 or 21 rounds?

Hashing twice does not give you the same security benefit as doubling the number of rounds. Suppose you find a collision in the original hash function. If we change the number of rounds, your collision probably won't be a collision any more. However, if we just "hash the hash", it's still a collision.
