### ISSUE TITLE
Compilation error for C

### ISSUE THREAD

**Issue by alphaonex86** [BLAKE3-team/BLAKE3#71]
Hi, I have this compilation error for C version:

gcc -O3 -Wall -Wextra -std=c11 -pedantic  -c blake3_sse41.c -o blake3_sse41.o -msse4.1
gcc -O3 -Wall -Wextra -std=c11 -pedantic  -c blake3_avx2.c -o blake3_avx2.o -mavx2
gcc -O3 -Wall -Wextra -std=c11 -pedantic  -c blake3_avx512.c -o blake3_avx512.o -mavx512f -mavx512vl
gcc -O3 -Wall -Wextra -std=c11 -pedantic  blake3.c blake3_dispatch.c blake3_portable.c main.c blake3_sse41.o blake3_avx2.o blake3_avx512.o -o blake3
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/ccCfPl6z.o: warning: relocation against `g_cpu_features' in read-only section `.text.startup'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/ccCfPl6z.o: in function `main':
main.c:(.text.startup+0x22b): undefined reference to `get_cpu_features'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: main.c:(.text.startup+0x275): undefined reference to `g_cpu_features'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: warning: creating a DT_TEXTREL in object
collect2: error: ld returned 1 exit status
make: *** [Makefile:35: all] Error 1

**Comment by oconnor663** [comment]
Out of curiosity, what was the problem?

**Comment by alphaonex86** [comment]
I wish include it as, be before then I had to do benchmark.
https://catchchallenger.first-world.info/wiki/Benchmark_for_conception#Hash
Then I keep with sha224/sha256 in my code, only xxhash have interesting usage for me (on some segment I need performance and not security to detect changed file, after the whole folder is check with real cryptographic hash).
