### ISSUE TITLE
largest output for blake3_hasher_finalize in c

### ISSUE THREAD

**Issue by sken77** [BLAKE3-team/BLAKE3#73]
I read the paper that blake3 can do up to 4gb of output. In c, is this achieved through batching calls of `blake3_hasher_finalize`? if so what is the largest size that function would handle?

A bit unrelated. does Rust uses some kind of streaming for doing this? I'm not familiar with rust, so a simple high level explanation on how the code does it would be great.

Thanks!

**Comment by oconnor663** [comment]
4 GiB is 2<sup>32</sup> bytes, but as described in the paper, BLAKE3 can output up to 2<sup>64</sup>-1 bytes. That is, about 18 *billion* gigabytes of output. Generally, 2<sup>64</sup> bytes is enough that you can treat it as unlimited. For comparison, the maximum input length of SHA-256 is 2<sup>64</sup> bits, and no one ever worries about exceeding that limit.

The C API doesn't currently expose a way to stream that output. If there's demand for it, probably what I'll add is something like a `blake3_finalize_seek` function, which takes an additional argument specifying a starting point somewhere in the stream. Then you could make multiple calls to `blake3_finalize_seek` in a loop, and get as much output as you want without allocating all that memory in advance. But that function hasn't been added yet. (The Python code at https://github.com/oconnor663/blake3-py exposes basically this interface.)

The Rust API does include a streaming interface: https://docs.rs/blake3/0.2.2/blake3/struct.OutputReader.html. You call `Hasher::finalize_xof`, and you get an `OutputReader` object. That object implements the `std::io::Read` trait, which is the idiomatic Rust way to say "you can read a stream of bytes from this object." It also implements `std::io::Seek`.

**Comment by oconnor663** [comment]
Are you building a streaming wrapper? Would something like `blake3_finalize_seek()` in the C API be useful to you today?

**Comment by sken77** [comment]
Oh you are right, i read it too fast. 

I was planning on supporting `update` up to max size of an byte array (2^32 bits), and use `ByteArrayInputStream` to be the `hash` equivalent in rust. Then batch the bytes into arrays and pass that to `blake3_update`. As for the output, it would be nice to have a way to stream it. is it difficult to implement? 

I have more questions but i will read the paper tonight more carefully and come up with some tomorrow. Thanks!

**Comment by oconnor663** [comment]
Definitely not difficult to implement. I should probably do it anyway.

**Comment by oconnor663** [comment]
Ok, I've added a `blake3_hasher_finalize_seek` function in a4ceef3932154db83752c16a21c51266bd9c561b. Let me know if you get a chance to try it.

**Comment by sken77** [comment]
wow nice. that was fast. im finishing testing the json test vectors through Java. ill try it after im done with that

**Comment by oconnor663** [comment]
Going to close this one for now, but please let me know if any other issues come up.
