### ISSUE TITLE
Compiler warnings: -Wmissing-prototypes

### ISSUE THREAD

**Issue by dlegaultbbry** [BLAKE3-team/BLAKE3#76]
When enabling this option I get a lot of hits in the various C code

../../dist/crypto/blake3/blake3_avx512.c:292:6: warning: no previous prototype for 'blake3_compress_xof_avx512' [-Wmissing-prototypes]
 void blake3_compress_xof_avx512(const uint32_t cv[8],
      ^~~~~~~~~~~~~~~~~~~~~~~~~~

Would it be possible to make sure all functions are either local to a module and static or defined in a header?

**Comment by oconnor663** [comment]
Sure, we have some declarations in `blake3_dispatch.c`, and we could probably move those out into a header file.

**Comment by sneves** [comment]
https://github.com/BLAKE3-team/BLAKE3/commit/eec458d03ee7828225dda4f08138563d4ff8bb6d

**Comment by oconnor663** [comment]
I wonder if I should add something like `-Werror -Wmissing-prototypes` to all of our compiler invocations in CI. Any other best-practice flags you guys know of?

**Comment by sneves** [comment]
For what it's worth, I think `-Wmissing-prototypes` is one of the most pointless warnings you can enable. In fact it is not enabled with `-Wall -Wextra` for good reason---it's highly noisy, and rarely if ever finds real bugs.

**Comment by oconnor663** [comment]
Fair enough. I'm going to go ahead and close this one.
