### ISSUE TITLE
provide compiled binaries for b3sum

### ISSUE THREAD

**Issue by oconnor663** [BLAKE3-team/BLAKE3#78]

**Comment by sergeevabc** [comment]
At last!

**Comment by oconnor663** [comment]
Done! See [the releases page](https://github.com/BLAKE3-team/BLAKE3/releases). I've sanity checked these by running them on my own machines, and they seem to work, but I'd love to have other folks kick the tires too. Also I haven't done anything fancy with the binaries apart from building with `--release` (I haven't even stripped symbols), so if there are any Best Practices I'm missing please let me know.

**Comment by sergeevabc** [comment]
@oconnor663, it kinda works, but slow as hell.

**Comment by oconnor663** [comment]
@sergeevabc I'd like to help you figure out the problem, but I can only do that if you give me the details of what you're measuring. (There's an unfortunate trend in online tech discussions, where A asks a question without any details, and B asks for details, and then later A comes back with details. That makes answering the question take days instead of minutes. If the "more details" cycle needs to repeat a few times, it could take weeks. The only way to break this cycle is to give _way_ more detail than you think you need to in the very first step.)

**Comment by sergeevabc** [comment]
Almost a year passed, b3sum has grown from 0.3.5 to 0.3.7 and I tried to calculate a hash again, now using 4.5 GiB rip of “[City lights][1]”. Especially I was eager to see how SSE2 tweaks had improved the performance (my CPU does not support SSE4+). Alas, in less than 30 seconds [Process Hacker][4] indicated 99% consumption of memory, than disk trashing began and I lost control for a few minutes. This is unacceptable as no other hashing app ([digest][1], [gohash][2], [rhash][3] to name a few), be it conservative or contemporary algorithm, caused such a disaster. As a last-ditch attempt I tried your advice about `<` or `--num-threads=1`, and it finished the job with less troubles.  Question is how do we proceed from here?

[1]: https://sourceforge.net/projects/filedigest/
[2]: https://github.com/martinlindhe/gohash
[3]: https://sourceforge.net/projects/rhash/
[4]: https://wj32.org/wp/software/process-hacker/
