### ISSUE TITLE
Callable from C (no_mangle pub extern as in c_neon)

### ISSUE THREAD

**Issue by rurban** [BLAKE3-team/BLAKE3#8]
Would it be possible to export the fast mt versions from Rust to C/C++, to compare against the single-threaded C version? I'm pretty sure many C/C++ projects would want to use the faster rust versions.

I'd also want to compare the C versions against the rust versions in smhasher.

**Comment by oconnor663** [comment]
I'm leaning towards experimenting with this as a separate crate at first. If we find it's getting some users, and merging the two repos would simplify maintenance, maybe we could do that in the future?

My instinct is that most C users are going to strongly prefer the pure C version, to avoid taking a dependency on `rustc`. We also plan to spruce that version up in the coming weeks, and the performance gap between the two might close at some point.
